pwntester/octo.nvim

- lua/octo/commands.lua
- lua/octo/completion.lua
- lua/octo/constants.lua
- lua/octo/gh.lua
- lua/octo/highlights.lua
- lua/octo/init.lua
- lua/octo/log.lua
- lua/octo/menu.lua
- lua/octo/navigation.lua
- lua/octo/signs.lua
- lua/octo/util.lua
https://github.com/trixnz/lua-fmt
Only setting indentation to 2, rest is default
`luafmt -i 2`
Might be nice to add this as a github action
fix #37
> Formatted the code with luafmt

- lua/octo/date.lua
- lua/octo/init.lua
- lua/octo/util.lua
- plugin/octo.vim
I tried to only copy the date stuff that's needed, but the code is not really modular.
Everything depends on everything..
It's not that big, I think it's acceptable to just include the whole thing. What do you think?
Also there should probably be a way to configure the formatting
resolve #38
> Add lua-date to format dates

- lua/octo/commands.lua
format the checks output as nice table
> make checks popup look nicer

- lua/octo/commands.lua
- plugin/octo.vim
command line completion for `Octo` command
For now just the basic commands.
This could be made smarter to also autocomplete issue number after `Octo issue edit` etc
> Add command completion

- lua/octo/commands.lua
- lua/octo/gh.lua
- lua/octo/graphql.lua
- lua/octo/init.lua
- lua/octo/menu.lua
- lua/octo/reviews.lua
- lua/octo/util.lua
- lua/octo/writers.lua
- plugin/octo.vim
> Add review support

- README.md
- lua/octo/commands.lua
- lua/octo/reviews.lua
Update README.md to document how to review PRs and view reviews
> Documentation updates

- README.md
- lua/octo/commands.lua
- lua/octo/entry_maker.lua
- lua/octo/graphql.lua
- lua/octo/init.lua
- lua/octo/menu.lua
- lua/octo/previewers.lua
- lua/octo/reviews.lua
- lua/octo/signs.lua
- lua/octo/util.lua
- lua/octo/writers.lua
- plugin/octo.vim
> Synched review comments

- lua/octo/gh.lua
- lua/octo/reviews/file-entry.lua
> remove ansi escape sequences from gh response

- README.md
- lua/octo/commands.lua
- lua/octo/graphql.lua
- lua/octo/telescope/menu.lua
- lua/octo/utils.lua
> Reuse checkout_pr function that does not depend on gh

- lua/octo/mappings.lua
Fixes the issue described in #186 
Fixes #186
Changed the function name to the function name used in the command section
The key mapping should work now before hand it did not work.
None
> Fix for issue #186

- README.md
- lua/octo.lua
- lua/octo/commands.lua
- lua/octo/config.lua
- lua/octo/gh.lua
- lua/octo/graphql.lua
- lua/octo/mappings.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/model/thread-metadata.lua
- lua/octo/navigation.lua
- lua/octo/telescope/menu.lua
- lua/octo/utils.lua
- lua/octo/writers.lua
- plugin/octo.vim
PR created with new `Octo pr create` :smile:
> Add `Octo pr create` command

- lua/octo/mappings.lua
Try and fix some mappings. closes #191.
I'm using stylua so it auto formatted the buffer a bit. I strongly
propose to use stylua and @pwntester if you like, I can set it up in
another pr.
> 🐛 FIX: mappings commands

- README.md
> Fix whitespace in table

- lua/octo/init.lua
- lua/octo/pickers/telescope/provider.lua
- lua/octo/utils.lua
> better handling of paginated results

- lua/octo/reviews.lua
- lua/octo/reviews/file-entry.lua
- lua/octo/reviews/layout.lua
- lua/octo/writers.lua
> better handling of renamed and added files in PRs

- lua/octo/ui/bubbles.lua
- lua/octo/writers.lua
previous to this commit viewing a repo on my day job's repo produced the
following error:
Error executing vim.schedule lua callback: ...e/louis/.config/nvim/after/oc
to.nvim/lua/octo/colors.lua:188: attempt to index local 'rgb_hex' (a userda
ta value)
...e/louis/.config/nvim/after/octo.nvim/lua/octo/colors.lua:188: in
function 'create_highlight'
...uis/.config/nvim/after/octo.nvim/lua/octo/ui/bubbles.lua:57: in
function 'make_label_bubble'
.../louis/.config/nvim/after/octo.nvim/lua/octo/writers.lua:66: in
function 'add_details_line'
.../louis/.config/nvim/after/octo.nvim/lua/octo/writers.lua:141: in
function 'write_repo'
...nfig/nvim/after/octo.nvim/lua/octo/model/octo-buffer.lua:96: in
function 'render_repo'
/home/louis/.config/nvim/after/octo.nvim/lua/octo/init.lua:233: …
> fix: fix repo view

- README.md
Update information in README about available keys for filtering PRs and Issues (not every key is available for PRs). Add FAQ entry about using the search query.
Fixes #281 
Edited README 😄 
Open file in preview ;)
> Update README - filtering keys, using search query

- lua/octo/model/octo-buffer.lua
- lua/octo/reviews/file-entry.lua
- lua/octo/reviews/file-panel.lua
- lua/octo/reviews/init.lua
- lua/octo/utils.lua
> fix 299: validate mappings are not null

- lua/octo/pickers/telescope/entry_maker.lua
- lua/octo/pickers/telescope/provider.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
* Display repository in Issue/PR preview https://github.com/pwntester/octo.nvim/commit/a26ae0707beb91d8590de1b1c66626bb84ff40e7
* Make `provider.search` to allow several prompts https://github.com/pwntester/octo.nvim/commit/8f5ea9f8c97209aabc36b711ffb31b3209d6b7a4
* Differ between Issue/PR after former change printing icons in telescope entries https://github.com/pwntester/octo.nvim/commit/f210e1aad020ff35f8d7b329e587a39ce8d3e3a3
I don't think so.
Randomly typing on a keyboard.
```lua
vim.cmd [[ 
\ command! TestProvider :lua 
\ require("octo.pickers.telescope.provider").search {
\    prompt = {
\       "repo:pwntester/octo.nvim is:pr is:open",
\       "repo:pwntester/codeql.nvim is:issue is:open",
\   }
\ } ]]
```
> Several nits

- .github/workflows/lint.yml
- README.md
- lua/octo/commands.lua
- lua/octo/completion.lua
- lua/octo/config.lua
- lua/octo/gh/graphql.lua
- lua/octo/pickers/telescope/provider.lua
> sort issues and PRs desc

- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
> fix: remove null nodes from timeline

- README.md
- lua/octo/config.lua
- lua/octo/reviews/file-entry.lua
Add `timeout` param to config to have a custom timeout for processes that can take time.
Resolves this https://github.com/pwntester/octo.nvim/issues/375 and should probably resolves : https://github.com/pwntester/octo.nvim/issues/369
I just added a new entry from the configuration, and call it inside the FileEntry function
> feat: added a timeout param to be able to configure long process time

- README.md
Follow up for https://github.com/pwntester/octo.nvim/pull/372 
I noticed that forgot to add new action into readme, sorry
> Agg go to file support to review_diff.

- lua/octo/utils.lua
To get remotes, the current build calls `git remote show` and `git remote <name>` multi times. Now it calls `git remote -v` only once and can get all results from this.
> refactor: call git only once to get remotes

- lua/octo/commands.lua
- lua/octo/completion.lua
- lua/octo/config.lua
- lua/octo/gh/graphql.lua
- lua/octo/gh/init.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/navigation.lua
- lua/octo/picker.lua
- lua/octo/pickers/fzf-lua/entry_maker.lua
- lua/octo/pickers/fzf-lua/log.lua
- lua/octo/pickers/fzf-lua/pickers/actions.lua
- lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua
- lua/octo/pickers/fzf-lua/pickers/assignees.lua
- lua/octo/pickers/fzf-lua/pickers/changed_files.lua
- lua/octo/pickers/fzf-lua/pickers/commits.lua
- lua/octo/pickers/fzf-lua/pickers/fzf_actions.lua
- lua/octo/pickers/fzf-lua/pickers/gists.lua
- lua/octo/pickers/fzf-lua/pickers/issue_templates.lua
- lua/octo/pickers/fzf-lua/pickers/issues.lua
- lua/octo/pickers/fzf-lua/pickers/labels.lua
- lua/octo/pickers/fzf-lua/pickers/pending_threads.lua
- lua/octo/pickers/fzf-lua/pickers/prs.lua
- lua/octo/pickers/fzf-lua/pickers/repos.lua
- lua/octo/pickers/fzf-lua/pickers/review_commits.lua
- lua/octo/pickers/fzf-lua/pickers/search.lua
- lua/octo/pickers/fzf-lua/pickers/users.lua
- lua/octo/pickers/fzf-lua/pickers/utils.lua
- lua/octo/pickers/fzf-lua/previewers.lua
- lua/octo/pickers/fzf-lua/provider.lua
- lua/octo/ui/writers.lua
This PR implements the remaining pickers for fzf-lua (started in https://github.com/pwntester/octo.nvim/pull/396).
- Actions
- Assigned labels
- Assignees
- Gists
- Issue templates
- Labels
- Pending threads
- Repos
- Review commits
- Search
- Users
Fixes #206
Same as the previous PR, I followed similar patterns. There are a few updates here to the original pickers. As I learned more about fzf-lua I found better ways to make the UI more responsive by utilizing callbacks to populate the picker rather than waiting on the `gh` response.
I've also moved away from the `formatted_*` tables that some pickers use since the data required can just be held in a single line and masked. For instance, when selecting a user the line behind the scenes looks like `<id> <login>` but the UI just shows …
> feat: fzf-lua picker, phase 2

- lua/octo/utils.lua
Fix the bug mentioned in https://github.com/pwntester/octo.nvim/issues/431
Closes https://github.com/pwntester/octo.nvim/issues/431
> Respect the order of `default_remote`

- lua/octo/pickers/telescope/provider.lua
- lua/octo/ui/bubbles.lua
- lua/octo/ui/colors.lua
> Upgrade to get_hl_color

- README.md
This commit fixes a type error on the configuration outlined in the readme. I noticed it when doing type validation in another PR
> docs: Fix `always_select_remote_on_create` type

- lua/octo/gh/graphql.lua
- lua/octo/ui/writers.lua
This commit shows who resolved the thread on the buffer
Signed-off-by: Liam Jarvis <jarviliam@gmail.com>
Closes: #463
> feat: Show resolved by on review threads

- lua/octo/gh/graphql.lua
Fixes #453 by adding missing `isDraft` attribute
> add missing isDraft attribute to the PR query

- README.md
- lua/octo/config.lua
- lua/octo/mappings.lua
This PR add a command `rebase_and_merge_pr` and provides a mapping to it. 
I followed the example of `squash_and_merge_pr`. The function implementing the `merge_pr` command already supports a rebase flag, only the command is missing.
> feat: add mapping for rebase_and_merge_pr

- README.md
> Quick typo fix "read:proejct" in readme

- lua/octo/gh/init.lua
> fix(projv2): check if v2 projects should be used

- doc/octo.txt
PR REVIEW section has a line swapped around. 
NONE
Just a doc edit.
Open the help text, read it and notice it makes more sense now :D
> Fix swapped lines in docs

- lua/octo/config.lua
Allows function type for `gh_env`
Fixes #549 
Update the validator. The rest was already in place and unchanged.
Use a function for `gh_env` that returns a table and ensure the plugin still works
> fix: Allow function type for `gh_env`

- lua/octo/navigation.lua
At present, "go to file" expects the file to be located relative to the current working directory.  This commit still looks for the file at the current directory, but falls back to using the git root path.  This enables "go to file" when the user is at a path inside the repository.
Fixes #539
As above, fallback to using the git root path to find files.
1. `cd` into a subdirectory of a git repository
2. Open a PR in Octo that has comments with tagged files
3. Press `gf` on one of those comments and it will now successfully take you to the tagged file
> fix: "go to file" falls back to finding the file from the git root

- README.md
This PR attempts to help alleviate some confusion that some users (like me) might have due to the minimum neovim version not being specified.
Fixes #557.
Just decided to add `Neovim >=0.10.0` in the README.md.
> Update README.md to include the minimum neovim version

- lua/octo/commands.lua
The PR allows user to leave a blank input for the label color and a random color will be generated like in `:Octo label create ...`
Closes #560
Please let me know if I can add some type of test
> Random color instead of empty string for `label create`

- lua/octo/utils.lua
Improves grammar of time ago to include singular instances (day, hour, etc...)
Fixes #579
Conditional check on the time spans before returning the text.
View a comment that was "1 day ago". I confirmed this works!
This is a pretty procedural fix, let me know if you want a more programmatic approach.
> fix: grammar of a singular amount ago

- lua/octo/gh/graphql.lua
- lua/octo/reviews/init.lua
> fix: escape new line in graphql query

- .github/PULL_REQUEST_TEMPLATE.md
> Add checklist for PRs

- lua/octo/gh/graphql.lua
> fix: remove escape_char since we are now using """ quoted strings

- lua/octo/gh/graphql.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
Adds combined status of checks for PR (it's nice to know if it's green or red)
NONE
See PRs for this repo. Also see ones for some repo without checks to ensure that there's no "Checks" section.
> display combined status of checks for pr

- lua/octo/gh/graphql.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
Following up on #660 adds "Merge" section to PR view—it's nice to see if you can merge with commit or squash/rebase, etc).
I capitalized checks message as well, IMO it looks good:
NONE
See different PRs with no reviews, conflicts, etc.
> display merge state in PR

- lua/octo/gh/init.lua
Fixes [this problem](https://github.com/pwntester/octo.nvim/pull/667#issuecomment-2457477283) introduced in #667
NONE
The debug message was removed
Doesn't apply
> fix: remove debug message

- README.md
- lua/octo/config.lua
- lua/octo/mappings.lua
- lua/octo/reviews/file-entry.lua
- lua/octo/reviews/layout.lua
- **fix: do not trigger ftplugins for local fs**
- **feat: make review focus configurable**
> Add config option to chose which buffer to focus on diff open

- lua/octo/ui/writers.lua
> Fix Mirrored typo

- lua/octo/ui/writers.lua
Remove the single quote in front of the commit message
Remove in the virtual text
View any PR buffer and see the commit message
> Remove non-closed single quote

- README.md
- lua/octo/config.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/bubbles.lua
- lua/octo/ui/writers.lua
Support for case where there is a deleted user for issues and PRs. 
Works in both the issue / Pr buffers as well as the summary upon popup
Closes #704
- Add ghost icon
- Use logic which the user is nil
Check out an issue or PR where the user is deleted
> Support for ghost users

- lua/octo/commands.lua
- lua/octo/gh/graphql.lua
Allows for stateReason specification
API: 
`:Octo issue close DUPLICATED`
`:Octo issue close NOT_PLANNED`
`:Octo issue close COMPLETED`
Or 
`:lua require("octo.commands").change_state("DUPLICATED")`
> [!NOTE]
>
> Will need to merge *after* #716
> Specify closing reason

- lua/octo/commands.lua
Follow up to #772 for specified label
> Label input case for multiselect

- lua/octo/gh/init.lua
- lua/octo/reviews/init.lua
- lua/octo/utils.lua
- Modify gh.run job:sync() to include missing conf.timeout
- Modify reviews.checkout_pr_sync() to include missing conf.timeout
Fixes #737
> fix: add missing timeout passthrough

- lua/octo/gh/graphql.lua
- lua/octo/ui/writers.lua
Display the author of the commit if the commit user is NIL
Closes #731
- Pull down the data 
- Add logic to the writer
Take a PR that has merge commit from the GitHub UI
For example: #702
> 731 merge commit author is not shown

- lua/octo/gh/fragments.lua
- lua/octo/gh/graphql.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/pickers/telescope/entry_maker.lua
- lua/octo/ui/colors.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
Adds rending of the: 
- ConnectedEvent
- CrossReferencedEvent
to see when PRs or Issues have been references from other PRs or Issues.
Related to #680
- Add to graphql queries
- Add writers
- Add condition on octo-buffer
Check out various Issues and PRs that display that information.
#731 has a PR that will close it
#680 has a PR that references it
#733 has a Issue that will be closed by it
> Add referencing events

- lua/octo/utils.lua
This refactors develop command to use gh.run instead of Job so there is less duplicatation
> Refactor develop command to use gh.run

- lua/octo/gh/fragments.lua
- lua/octo/gh/graphql.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
The milestone and demilestone events are missing from Issues and PRs
Closes #748
Pull data, create writer, and render
Check out issues and PRs that have milestones and see it in the timeline
> Add milestone events to timelines

- lua/octo/gh/fragments.lua
- lua/octo/gh/graphql.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
Commits that reference issues were not being displayed. This renders the "ReferencedEvent" which contains that information
Closes #774
Add fragment and add it to issue timeline events. 
Add logic to render
Checkout out issues that have referenced events. Like #717
> add ReferencedEvent to issue timeline

- lua/octo/gh/fragments.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
> 735 add commit status checks to event

- .github/workflows/labels.yml
> add workflow to add closing labels

- lua/octo/gh/graphql.lua
- lua/octo/pickers/telescope/provider.lua
Simple refactor to use gh.graphql
> Refactor discussion query

- lua/octo/ui/writers.lua
Case for if a project doens't have a name
Case when there is nil project name
Find an (old) issue where there is no project name
> Project without name

- lua/octo/utils.lua
I noticed that PR branch detection for `Octo review resume` was not working for some PRs. 
Missed the fact that `gh cli` may store upstream branches via a format that reflects the pull request. 
Updates the previously merged functions in #806 to parse this format. 
---
A follow up to: #806
I overlooked that the `gh cli` command may also store checked out local branch's upstream branch in a format 'refs/pull/{pr_number}/head'.
Update the `get_upstream_branch_from_config` function to consider this and check if the current branch's upstream configuration matches the pr datamodel being evaluated.
> fix: detect pr branch with 'refs/pull/' branch config settings

- lua/octo/commands.lua
- lua/octo/navigation.lua
- lua/octo/pickers/telescope/entry_maker.lua
Used the Lsp references for the `get` and `get_<kind>` to find the last remaining.
> fix: change renaming order swap

- lua/octo/commands.lua
`Octo label create` can be used from any file as long as the repo can be determined
> Create label from repo

- README.md
Add snacks.nvim to README.md installation section.
NONE
> feat(docs): add snacks.nvim to installation section

- lua/octo/gh/init.lua
- lua/octo/utils.lua
- lua/tests/plenary/gh_spec.lua
- Allow for _ in keys which are replaced by -. For example add_milestone -> --add-milestone CLI flag
- Refactor to use gh.issue.edit / gh.pr.edit API
> Refactor milestone logic

- lua/octo/gh/init.lua
> add PUT command to REST API wrapper

- lua/octo/gh/init.lua
> Add typing to gh.run

- lua/octo/commands.lua
> Migrate gh pr checks logic

- lua/octo/commands.lua
Changes: 
- update to use jq and put process on GitHub
- use newer callback helper
- Say "Pull Request" instead of "Issue"
> Use jq and callback in state change

- lua/octo/utils.lua
> Refactor template logic'

- lua/octo/gh/graphql.lua
- lua/octo/utils.lua
Switching on queries to use fields and some jq filters
> Refactor various utils queries to use jq

- lua/octo/gh/graphql.lua
- lua/octo/navigation.lua
- **parameterize query**
- **use the new api**
> refactor issue navigation

- lua/octo/pickers/telescope/provider.lua
- lua/octo/utils.lua
- lua/tests/plenary/utils_spec.lua
- **handle pagination**
- **refactor to new API**
Issue with the pagination
> 802 error on large number of discussions

- lua/octo/init.lua
- lua/octo/pickers/telescope/entry_maker.lua
- **error while loading repo buffer**
- **entry with the list picker**
Two errors that I ran into. The repo buffer wasn't creating correctly using the graphQL query and The picker wasn't using the correct repo value
> Repo Buffer not rendering and repo list not passing correct filename

- lua/octo/commands.lua
- lua/octo/completion.lua
- lua/octo/init.lua
- lua/octo/mappings.lua
- lua/octo/navigation.lua
- lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua
- lua/octo/pickers/fzf-lua/pickers/assignees.lua
- lua/octo/pickers/fzf-lua/pickers/changed_files.lua
- lua/octo/pickers/fzf-lua/pickers/commits.lua
- lua/octo/pickers/fzf-lua/pickers/project_cards.lua
- lua/octo/pickers/fzf-lua/pickers/project_cards_v2.lua
- lua/octo/pickers/fzf-lua/pickers/project_columns.lua
- lua/octo/pickers/fzf-lua/pickers/project_columns_v2.lua
- lua/octo/pickers/telescope/provider.lua
- lua/octo/reviews/init.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
Consolidates getting the current octo buffer with `utils.get_current_buffer()`
Related to #742
> Expose current_buffer logic

- lua/octo/gh/queries.lua
- lua/octo/pickers/telescope/provider.lua
All of the users where not showing up with assignable / mentionable. This leverages jq before the parsing the output.
> BUG: Not all users showing up

- lua/octo/gh/fragments.lua
- lua/octo/gh/mutations.lua
- lua/octo/gh/queries.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
Add both pinned and unpinned items to the timeline
- **update the queries, mutations, and fragments**
- **add logic to write**
- **add to timeline**
> Add pinned and unpinned events to timeline

- lua/octo/gh/fragments.lua
- lua/octo/gh/mutations.lua
- lua/octo/gh/queries.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
- **add the required grahpql**
- **handle the logic like labels**
- **add the writer logic**
> Add subissues to timeline

- lua/octo/gh/fragments.lua
- lua/octo/gh/mutations.lua
- lua/octo/gh/queries.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
This adds a parent issue and related events to the timeline.
See #934 as an example of an issue with a parent issue.  
- **add the parent issue fragments**
- **render in timeline**
- **add writer logic**
> Add parent issues to timeline

- lua/octo/ui/colors.lua
This expands upon #940 and adds the linked highlight groups as well.
> Add the linked highlight groups to the helper as well

- lua/octo/ui/writers.lua
Just removing the additional space at the end
> Remove extra space at end of "[DRAFT]"

- lua/octo/pickers/telescope/entry_maker.lua
- lua/octo/pickers/telescope/previewers.lua
- lua/octo/pickers/telescope/provider.lua
- lua/octo/utils.lua
Discussions will now show up in the telescope notifications picker. The discussion buffer will be opened upon selection.
> 920 add discussion to notifications

- README.md
- doc/octo.txt
- lua/octo/commands.lua
- lua/octo/gh/mutations.lua
Add `reopen` command for discussions
- **add the mutation to reopen a discussion**
- **implement the new command**
- **add documentation for the commands**
> Add `:Octo discussion reopen` command

- lua/octo/commands.lua
- lua/octo/constants.lua
- lua/octo/utils.lua
- lua/tests/plenary/utils_spec.lua
Octo <discussion-url> now works
- **adjust the regex**
- **branch when discussion**
- **add some tests**
> 949 octo discussion url does work

- lua/octo/model/octo-buffer.lua
- lua/octo/pickers/telescope/previewers.lua
- lua/octo/ui/writers.lua
This matches the issue and PR buffers now and is easier to navigate with discussion searches
- **add in the repo to the details**
- **shift the body one line down**
> Add repo to Discussion buffer details section

- lua/octo/completion/init.lua
- lua/octo/completion/search.lua
Makes it easier to search for issues, PRs, and discussions by adding completions to the qualifiers. 
https://github.com/user-attachments/assets/cdb45c72-3173-4db8-8ab3-eb73ec1bad47
Related to https://github.com/pwntester/octo.nvim/discussions/502
Does this accomplish what you were looking for @Enigama
- **add search completion**
- **add some docs and variable names**
- **consolidate the branch logic**
- **completion for categories**
Use `Octo search` or `Octo issue/pr/discussion search` and start pressing <Tab> to see the completions.
> search completions

- lua/octo/model/octo-buffer.lua
- lua/octo/pickers/telescope/previewers.lua
Add the virtual text for the state and number to match what is used in Issues and PRs
> add discussion state and number virtual text

- lua/octo/ui/colors.lua
> fix: add back fg

- lua/octo/model/octo-buffer.lua
- lua/octo/pickers/telescope/previewers.lua
- lua/octo/ui/writers.lua
- lua/octo/utils.lua
Add the total replies to the summary at the top
- **sum the replies**
- **add to writer**
- **increase the number after having new line**
> Add discussion reply count to summary

- .github/workflows/labels.yml
The GitHub action location has changed
> Adjust action location

- .github/ISSUE_TEMPLATE/bug_report.md
- lua/octo/ui/writers.lua
Noticed while looking at https://github.com/pwntester/octo.nvim/issues/485
- **case when there is a reopen**
> reopen timeline bug

- README.md
> move examples toward top

- lua/octo/config.lua
- lua/octo/model/octo-buffer.lua
- lua/octo/ui/writers.lua
```
  williambdean added 3 commits 23 hours ago
  ✓ a221609 combine together
  ✓ 8620055 provide through configuration
   82c75bd Merge branch 'master' into group-commits-together
```
> Add commit header in timelineItems

- lua/octo/gh/queries.lua
- lua/octo/init.lua
- lua/octo/ui/writers.lua
Linked discussions will now have a popup summary like issues and PRs
Some tests discussions:
https://github.com/williambdean/latent-calendar/discussions/22
https://github.com/pwntester/octo.nvim/discussions/974
https://github.com/pwntester/octo.nvim/discussions/239
#253
And proof that issues and PRs still work:
#896 #997
> Add discussion popup

- lua/octo/pickers/telescope/provider.lua
This URL is closer to what is followed in the UI. Seems to be different for discussion
CC: @tris203 Can you give this a try. Maybe you have a better understanding of this endpoint and what is closest to UI
Closes #1005
> Use html_url for notification `<C-y>`

- .github/workflows/tests.yml
failing job noticed in https://github.com/pwntester/octo.nvim/pull/1000
Giving this a try to see if it fixes the failing CI/CD
> update CI/CD ubuntu version

- lua/octo/commands.lua
- lua/octo/gh/queries.lua
- lua/octo/workflow_runs.lua
New commands:
- `Octo workflow list`: List all the workflows and selects one to edit.
- `Octo workflow edit`: Like above but can be called from run buffer specifically.
Adds a way to edit the current workflow file. Also a picker to select a workflow file to edit.
CC: @GustavEikaas 
- **add query for files in directory ;**
- **add new command**
- **add the edit function**
> Workflow edit from run buffer

- lua/octo/navigation.lua
> nil value check before comment navigation

- lua/octo/commands.lua
- lua/octo/completion/search.lua
- lua/octo/gh/queries.lua
- lua/octo/pickers/fzf-lua/pickers/repos.lua
- lua/octo/pickers/telescope/entry_maker.lua
- lua/octo/pickers/telescope/provider.lua
Adds `Octo search is:repository <prompt>` and `Octo repo search <prompt>` functionality
> Support `Octo search is:repository <prompt>` and `Octo repo search <prompt>` functionality

- lua/octo/gh/queries.lua
- lua/octo/utils.lua
- **parameterize the query**
- **refactor query**
> refactor file context

- lua/octo/gh/queries.lua
- lua/octo/ui/writers.lua
Add `authorAssocation` to the query and render it in the details for PRs
This gives context about the author of the PR like in the UI.
- **add author association to query**
- **render in details**
Check out any PR and see the author association in the details
> Add author association to PR details

- lua/octo/utils.lua
A different laugh emoji was in the README, keymap help, and what is displayed
> Consolidate laugh emoji

- README.md
- doc/octo.txt
- lua/octo/commands.lua
- lua/octo/navigation.lua
Adds the `browser` command for discussions like with the other buffer types
> Add `Octo discussion browser` command

- README.md
- doc/octo.txt
- lua/octo/commands.lua
- lua/octo/gh/mutations.lua
- lua/octo/gh/queries.lua
Adding commands to add and remove issueTypes
Closes #1102
Implement queries and mutations then add commands
Use the commands on issue buffers
> `Octo type add` and `Octo type remove` for issueTypes

- .pre-commit-config.yaml
- lua/octo/ui/writers.lua
> Account for "NONE" status in `authorAssociation`

- lua/octo/config.lua
Inspired by @PeterCardenas. Maybe you can take a quick look. I am new to these type hints.
Also, how can we expose the octo.config.OctoConfig? That isn't coming up with my LSP but other various do...
> Type hint merge method

- lua/octo/pickers/telescope/provider.lua
> fix: copy sha
