pwntester/octo.nvim

lua/octo/completion.lua, lua/octo/init.lua
This PR adds the ability to @mention people in the PR view. Related to #12. 
This works by accumulating a list of users from a couple different sources.
These include:
- The author of the issue
- The authors of existing comments
- The contributors to the repo
This list of users is currently only used to @mention people so the api call to
fetch collaborators is started in the background without waiting for it to
complete. The accumulated list is then attached to the issue buffer under the
key `taggable_users`.
If the completion base starts with `@` inside the completion function, the
entries will be built from the `taggable_users` that should be attached to the
buffer.
I also added keymaps in insert mode for `@` and `#` to make them immediately
call the completion menu.
#12 mentions …
=> Add @People mentioning to PR view

README.md, lua/telescope/_extensions/octo.lua
Currently, Trying to use Telescope octo command results :
```vim
vim/shared.lua:64: in function 'gsplit'
vim/shared.lua:111: in function 'split'
...re/nvim/site/pack/packer/opt/octo.nvim/lua/octo/menu.lua:460: in 
function <...re/nvim/site/pack/packer/opt/octo.nvim/lua/octo/menu.lua:448>
...pack/packer/opt/telescope.nvim/lua/telescope/command.lua:90: 
in function <...pack/packer/opt/telescope.nvim/lua/telescope/commands.lua
```
I wonder why is that :thinking:
=> add telescope interface

lua/octo/menu.lua
according to https://github.com/nvim-telescope/telescope.nvim/pull/472
=> update telescope actions

README.md, after/syntax/octo_issue.vim, lua/octo/commands.lua, lua/octo/entry_maker.lua, lua/octo/graphql.lua, lua/octo/init.lua, lua/octo/menu.lua, lua/octo/previewers.lua, lua/octo/reviews.lua, lua/octo/util.lua, plugin/octo.vim
Addresses #93 
Get rid of fugitive requirement and get file contents from GitHub API enabling online PR reviews that do not require to have repos locally
=> Online reviews

lua/octo/folds.lua, lua/octo/init.lua, lua/octo/writers.lua, plugin/octo.vim
Add manual folds for comments. By default all comments are unfolded.
Use `zc`/`zo` to close/open a fold, `zM`/`zR` to close/open all folds, etc.
=> add folds for comments

README.md, lua/octo/constants.lua, lua/octo/gh.lua
This PR adds basic support for Github Enterprise instances.
I briefly tested with the instance I have and the 'PR' and 'Issues" functions work as expected.
Gists do not, due to [underlying bug in GH CLI](https://github.com/cli/cli/issues/1745), there is a relatively easy [workaround available](https://github.com/cli/cli/issues/1745#issuecomment-694377743).
In fact, setting `GH_HOST` environment variable kinda renders this pull request useless because it makes the PR/issue commands work out of the box too so I would like to get your input/preferences on this.
=> add Github Enterprise support

lua/octo/menu.lua
Problem: In a production environment, it's common to have 1000s of PRs and unless I use a browser, I'm not going to know what is currently open and what is not. It's tedious to always type `Octo pr list states=OPEN`
Solution: default the state argument to "OPEN" - this matches the behavior of the gh-cli's `gh pr list` https://cli.github.com/manual/gh_pr_list
NONE
Added a default for `opts.states` in `menu.pull_requests`
1. Open vim
2. Run `Octo pr list` to verify that open works
3. Run `Octo pr list states=CLOSED` to verify that closed works
4. Run `Octo pr list states=MERGED` to verify that merged works
=> Default pr list to open prs

lua/octo/commands.lua, lua/octo/config.lua, lua/octo/graphql.lua, lua/octo/mappings.lua, lua/octo/model/pull-request.lua, lua/octo/reviews/file-entry.lua, lua/octo/reviews/file-panel.lua, lua/octo/util.lua
Adds support for toggling viewed state on PR changed files
Fixes https://github.com/pwntester/octo.nvim/issues/147
viewed state is collected as part of the PR load
on the review file panel, it is used to show an icon indicating if the file has been marked as viewed or not
A new mapping (`<leader><space>`) sends a GraphQL API mutation to change the viewed state and redraws the file panel
=> Support toggling changed file viewed state

lua/octo/menu.lua
This change brings about some consistency with with all the other Telescope's prompts, by setting the prompt title instead of the prefix. This also preserves users' custom prompt prefixes in case they have set any.
closes #150 
Running any of the Octo's commands should now show the "action" as a prompt title instead of the prefix.
What Octo's prompts look like:
What Telescope's inbuilt prompts look like (with a user-set prompt_prefix):
What Octo's prompts would be changed to (with a user-set prompt_prefix):
=> change prompt_prefixes to prompt_titles

lua/octo.lua, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/gh.lua, lua/octo/mappings.lua, lua/octo/model/octo-buffer.lua, lua/octo/model/thread-metadata.lua, lua/octo/navigation.lua, lua/octo/utils.lua, lua/octo/writers.lua, plugin/octo.vim
Enable a new navigation `goto_file` mapped to `gf` by default which navigates 
to the location of a thread if the file is available under the CWD
This new navigation is only enabled on PR buffers within a Thread block
- Refactor get_thread_at_cursor to return just a single object
- Add new `goto_file` config and default mapping `gf`
- Refactor get_comment_at_cursor to return a single obj
- Adjust thread start line
=> Enable `gf` on thread blocks

lua/octo/telescope/menu.lua
Checking out PR from `Octo pr list` does not work. The telescope entry is being interpreted incorrectly, `selection.value` is the PR number rather than a table.
Use the correct number when attempting to checkout a PR
Tested the change locally
=> Fix PR checkout from telescope list

lua/octo/mappings.lua
Checking out a PR got refactored in #184 and now the mapping points to a non-existing function in `commands.lua`.
No issue exists but happy to add one post-hoc if desired.
Changing what command `checkout_pr` in `mappings.lua` points to, namely `commands.pr.checkout`
Try checking out as is and you'll run into an error. This PR is a simple fix for that :)
=> fix: correct function checkout_pr points to

README.md
Adds syntax highlighting to the config and installation example in the README. 
No.
Adding `lua` as embedded language in the code block. 
Look at my fork [README](https://github.com/rafamadriz/octo.nvim/blob/master/README.md#-installation)
Some trailing white space in the README was removed.
=> add syntax highlighting to config and installation example in README

lua/octo/gh.lua
The error below is shown when we try to reach a GHE instance under a corporate proxy:
```
> :Octo issue list
Fetching issues (this may take a while) ...
git.mycompay.com
X git.mycompay.com: authentication failed
- The git.mycompay.com token in /Users/waltermaldonadojr/.config/gh/hosts.yml is no longer valid.
- To re-authenticate, run: gh auth login -h git.mycompay.com
- To forget about this host, run: gh auth logout -h git.mycompay.com
```
But it turns out authentication is working ok. What happens is that the gh client cannot reach the server under a corporate proxy. Passing in the env variables to the plenary job seems to fix the issue.
NONE
Added the variables in plenary job initialization, grabbing them from vim.env
You'll need to setup a proxy and configure your pc to only work …
=> Pass in proxy variables to plenary job

lua/octo/utils.lua
This PR changes the git command on `Utils.get_remote_name()` function to use the `git remote --get-url candidate`. It allows custom rewritten URLs in git config to work properly. See more: https://github.com/pwntester/octo.nvim/issues/228
Fixes #228 
It's a two-line code change. The first one substitutes the `git config --get remote.%s.url` command for `git remote get-url %s`. Since the new command returns an error message, the second line ignores every candidate with an error instead of verifying a nullability.
`Octo pr list` should work for all the git clone options bellow:
`git clone git@github.com:nandofarias/octo.nvim.git && cd octo.nvim && nvim +"Octo pr list"`
`git clone https://github.com/nandofarias/octo.nvim.git && cd octo.nvim && nvim +"Octo pr list"`
`git config --global …
=> Use git remote get-url

README.md, lua/octo/utils.lua
Fixes #230 
Checking for the string "error" can be problematic: 
- Firstly, errors can return other strings like "fatal", which will not be caught
- A repository url could contain error (e.g. my-error-checker.git or similar), and this will lead to false errors being caught
Using `/dev/null`, we can check for an empty string ignoring error messages.
I've tested it locally and it works for me.
Caveat: this obviously won't work with Windows machines, but not sure if we're supporting them anyway.
=> Fix error recognition for `git remote` command

.gitignore, doc/octo.txt
I wanted to quickly lookup some of the Octo commands with `:h` and realized it currently doesn't have a helpfile.
This PR adds one, based off the README.
Let me know what you think and if there are any edits you'd like me to make.
=> Add vim helpfile/doc

lua/octo/gh.lua
Allows the `GITHUB_TOKEN` env var to be sent through to `gh` when making calls out to it. This allows octo to work out of the box in environments where `GITHUB_TOKEN` is automatically set (Codespaces, for example).
Fixes https://github.com/pwntester/octo.nvim/issues/235
I added `GITHUB_TOKEN` to list of environment variables that gets passed to the job that calls out to `gh`
I ran my version of octo in a codespace where `GITHUB_TOKEN` was set and it worked.
=> Add gh token to env vars passed to gh to allow for token auth

lua/octo/reviews.lua, lua/octo/reviews/file-panel.lua, lua/octo/utils.lua
When `gh` returns multiple pages, the plugins break cause the output is not a JSON file but the concatenation of multiple JSON files.
NONE
One way to break it down is to use the `--jq` argument that will return each JSON content on a different page.
We can then split the returned content and populate the results object with all the PR files
I guess one could create a repo with a PR that generates multiple diffs to enforce the pagination.
For me it breaks with the following stack trace:
```
Error executing vim.schedule lua callback: Vim:E474: Trailing characters: ... stack traceback:
[C]: in function 'json_decode'
.../.config/nvim/plugged/octo.nvim/lua/octo/reviews.lua:149: in function 'cb'
.../.config/nvim/plugged/octo.nvim/lua/octo/gh.lua:83: in function 'cb'
```
After applying this …
=> Ensure all files from PR are loaded

README.md, lua/octo/commands.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
Adds an action that lists all available Octo actions and runs them when selected.
Fixes #163. 
1. Added a new top-level `Octo actions` action. This required adding support for actions without an object.
2. This iterates through each object in `commands.lua` and flattens them into an array that's then passed to the provider.
3. The provider renders each action with two columns: `object action`, e.g. `pr list`.
Run `Octo actions`.
This currently doesn't handle actions that require arguments like `issue create`. I see two options for that:
1. When building the `flattened_actions` array, we inspect the given action to determine if it requires an argument and then prompt the user for each argument.
2. Adjust existing actions that require arguments so they can be called without the argument, …
=> Add action to list all available Octo actions

README.md, doc/octo.txt
Updates the documentation to resolve a deprecation message from a recent treesitter change: https://github.com/nvim-treesitter/nvim-treesitter/commit/58a4897e6d5f21a9178ae0f802d47af26d67a219
```
used_by is deprecated, please use 'filetype_to_parsername'
```
Fixes #258 
Updated docs and README to use the new syntax `parser_config.markdown.filetype_to_parsername = "octo"`
Changed my neovim config locally to use `parser_config.markdown.filetype_to_parsername = "octo"` and the deprecated message vanished
=> Update docs to correct deprecated treesitter config

lua/octo/config.lua
To allow users to provide their own submit_win keymaps
Fixes #270 
Added the missing user mapping override
Provide a custom submit_win mapping to the configuration and expect it to be used in the submit window
=> Allow users to change the submit_win mappings

lua/octo/pickers/telescope/entry_maker.lua, lua/octo/utils.lua, lua/octo/writers.lua
By providing the filename as part of the entry, now a user can load multiple
entries from Telescope to the quickfix/loclist and actually move through them
and making Octo fill the buffers by triggering the BufReadCmd.
I don't see one, but I think this is an actual bug. Before this code if you tried filling the quickfix list you wouldn't get anything useful.
Break up editing function into uri generation and editing the uri.
1. `Octo issue list`
2. Select multiple with telescope
3. Use send to quickfix/loclist action.
4. Now navigation of the quickfix list has the buffer names, and Octo fills them.
I tested pull requests and issues, but not the repo one. Can't seem to make octo show me the repositores I own. Or perhaps I made a mistake?
=> feat: provide entry filename for better integration with nvim

lua/octo/commands.lua, lua/octo/gh.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/utils.lua
`gh api` gets confused if auth for a github.com host is configured, but
the repository remote uses an enterprise github host. We avoid this by
finding the host from the remotes and specify it via flag.
Fixes: https://github.com/pwntester/octo.nvim/issues/276
=> fix: specify hostname if remote is not github.com

lua/octo/reviews/init.lua
I had `vv` mapped to `v']` to select whatever was pasted last. This seems to not play well with the command `vvGk` in `Review:add_comment`. I kept getting the following error:
```
E5108: Error executing lua: .../.vim_run/plugged/octo.nvim/lua/octo/reviews/init.lua:404: Vim(normal):E20: Mark not set
[C]: in function 'cmd'
.../.vim_run/plugged/octo.nvim/lua/octo/reviews/init.lua:404: in function 'add_comment'
.../.vim_run/plugged/octo.nvim/lua/octo/reviews/init.lua:431: in function 'add_review_comment'
.../.vim_run/plugged/octo.nvim/lua/octo/mappings.lua:112: in function <.../.vim_run/plugged/octo.nvim/lua/octo/mappings.lua:111>
```
No.
Use `normal!` (with the `!` at the end) to use unmapped commands and avoid conflicts with user mappings
Map `vv` to `v']` in your …
=> Use unmapped commands when excuting normal mode commands

lua/octo/reviews/thread-panel.lua
Fixes creating thread buffers for existing comments.
When a comment is first created but before it's submitted, the `thread` object in `Review:add_comment` is stubbed with a valid value given for `originalStartLine`. `ThreadPanel:create_thread_buffer` then uses this to correctly render the thread.
But after submitting the comment, the response from the GH API doesn't include a value for `originalStartLine` for single-line comments, [as mentioned here.](https://docs.github.com/en/graphql/reference/objects#pullrequestreviewthread) This breaks the rendering in `create_thread_buffer`.
Fixes #314 
The fix was to fall back to `thread.originalLine` if `thread.originalStartLine` is set to `vim.NIL`.
1. Create and submit a new comment.
2. Move the cursor over the comment.
=> Fix create_thread_buffer

lua/octo/commands.lua, lua/octo/model/octo-buffer.lua, lua/octo/reviews/file-panel.lua, lua/octo/reviews/init.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
I updated my neovim to the `nightly` branch and broke `octo.nvim` when opening a PR.
Apparently `vim.fn.trim` is renamed to `vim.trim`.
Replace all occurences of `vim.fn.trim` to `vim.trim`
Open a PR with octo.nvim
I'm not sure if this PR should be merged for now since this is a fix for a nightly version of Neovim.
=> Update vim.fn.trim for nightly neovim

README.md, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/utils.lua
Adds config option `always_select_remote` that gives select prompt for base repo when creating a PR.
Fixes #334
I added function to get all configured remotes in the current repo, then I parse it and display it in `inputlist` and use it as base repo. This only happens if `always_select_remote` is set to `true`. Otherwise the behaviour is same as before.
Set `always_select_remote` to `true`
`:Octo pr create`
Prompt with remotes should be displayed
Select a repo from the list
Selected repo should be used as base repo for the PR
My lua skills are pretty basic, so feel free to suggest/make any improvements
=> Add option to select base repo

lua/octo/ui/window.lua
If the number of max lines >= 1, it calculates a float number. It could apply to `vim.api.nvim_open_win`. Add the converting action to make sure the final result type is int.
Pass the size with correct type to create floating window.
NONE
The result of the value may not be an integer, add the convert to make sure it's integer type.
I verify in my local environment with `:Octo pr checks`
=> Fix the floating window size calculation

README.md, doc/octo.txt, lua/octo/commands.lua
Add repo-review and review-close commands to the docs. Fixed a couple of typos while I
was at it.
Also added the heart reaction command, because I noticed it was missing, even though all
the docs referred to it as if it worked.
No
Updated doc/octo.txt and README to add the missing commands
N/A
=> Add missing commands to docs

README.md, lua/octo/config.lua, lua/octo/navigation.lua
This PR adds support for `go_to_file` in `review_diff`. 
Often during the review I want to harness the power of lsp and see some type info, or go to definition. Currently lsp in not attached to buffers during review. But I want to be able to go_to_file to be able to use it.
Also found this comment while browsing thought the project.
https://github.com/antosha417/octo.nvim/blob/92b982d7e2271597accfb3a6157a9f5efc185b24/lua/octo/reviews/file-entry.lua#L394-L400
Fixes https://github.com/pwntester/octo.nvim/issues/371
with default config press `gf` while in `review_diff`
Thank you a lot for maintaining this plugin and doing neovim community better ❤️
=> feature: review_diff go to file

README.md, lua/octo/autocmds.lua, lua/octo/config.lua, lua/octo/folds.lua, lua/octo/model/octo-buffer.lua
This PR adds to options to disable/enable the modified marks on the sign column.
The reason for this is to enable users to not use the signcolumn for marking modified comments/body/title so that they can use the statuscolumn instead.
Status column will be more customizable and does not suffer from https://github.com/pwntester/octo.nvim/issues/80
An an example you can disable the signcolumn using:
```lua
ui = {
use_signcolumn = false
}
```
and add the following to your statuscolumn configuration
```lua
local function mk_hl(group, sym)
return table.concat({ "%#", group, "#", sym, "%*" })
end
_G.get_statuscol_octo = function(bufnum, lnum)
if vim.api.nvim_buf_get_option(bufnum, "filetype") == "octo" then
if type(octo_buffers) == "table" then
local buffer = octo_buffers[bufnum]
if buffer then …
```
=> make signcolumn configurable

lua/octo/gh/init.lua
This PR is the logical extension of #220. If working with a configured corporate proxy and a GitHub host that does not require proxying since it is in front of the proxy, `gh` fails to authenticate since it tries to route through the proxy regardless.
```sh
$ printenv | grep '^\w\+_proxy='
http_proxy=http://proxy.mycompany.com:80
https_proxy=http://proxy.mycompany.com:80
no_proxy=localhost,127.0.0.1,.mycompany.com
```
```
> :Octo pr list
github.mycompany.com                                                                                                                                                                                               
X github.mycompany.com: authentication failed …
```
=> Pass in `no_proxy` to plenary job

lua/octo/utils.lua
Assigns 0 to offset values that were returned as `nil` from `string.match()` i.e. no `diff_directive` was found or was empty string.
Fixes #382 
Set `right_offset` and `left_offset` to `0` if values are equal to `nil`
Tested on a personal repo
=> Fix display offset values for empty diff directives

lua/octo/gh/init.lua
With this pr the local repo hostname is used to determine the Username for eg comments and other operations that need this username.
Fixes #388 
To determine the Username `gh auth status` is used, which also takes the flag `--hostname`. I added this flag to the `gh auth status` command with the remote host i get from the `get_remote_host` function from `octo.utils`.
If you have 2 hosts configured in ~/.config/gh/hosts.yml like github.com and a GHE instance, the current implementation only takes the first  output in consideration to determine the username, which in my test is always github.com even if this is the second host configured in ~/.config/gh/hosts.yml.
With adding the `--hostname` flag we only consider the local repos remote for determine the username.
You have 2 host configured …
=> Use hostname flag to get user name

README.md
nvim-web-devicons's organization `kyazdani42` is renamed to `nvim-tree`.
GitHub can resolve names even with old Org names, but some nvim plugin managers (e.g., lazy.nvim) issue warnings when both old and new names are included in the import. Therefore, I would like to standardize to the new name
"NONE"
rename nvim-web-devicons's URL.
We can access new URL https://github.com/nvim-tree/nvim-web-devicons and display new URL at GitHub.
=> refactor(README):rename org

lua/octo/constants.lua, lua/octo/init.lua, lua/octo/navigation.lua, lua/octo/utils.lua
I noticed both `goto_issue` and `on_cursor_hold` do not work with the latter issue when multi issues on one line.
```
See #12, #13
```
This PR solves this and slight bugs below.
* 4e68143 Now it can work with short issue style on the begging of the line.
- It did not work with `#12` on the begging.
* e1b9417 It had a mistake to calculate columns.
Run `goto_issue` and `on_cursor_hold` for each line and each issue/PR.
Short issue pattern: #393, #394, #395
Long issue pattern: pwntester/octo.nvim#393, pwntester/octo.nvim#394, pwntester/octo.nvim#395
URL issue pattern: https://github.com/pwntester/octo.nvim/pull/393, https://github.com/pwntester/octo.nvim/pull/394, https://github.com/pwntester/octo.nvim/pull/395
=> Improve goto_issue & on_cursor_hold

README.md
Rename "PR review" to "PR reviews" to be consistent with the table of contents.  The link to the section in the table of contents now works.
Fixes #402.
The link was broken because it did not match the section title.  It now does.
1. Open the link to the README in the fixed version: https://github.com/jcharum/octo.nvim/blob/5b223ddfc2e47711194bb121e3a99cfc887c7ba5/README.md .
2. Scroll to the Table of Contents.
3. Click on the `PR reviews` link.
4. Verify that it takes you to the `PR reviews` section.
None.
=> Rename "PR review" to "PR reviews"

README.md, lua/octo/commands.lua, lua/octo/config.lua
Provides a QOL feature to show the list of builtin actions when no action is provided.
Fixes #377 
Added the config option `enable_builtin` which when enabled runs `Octo actions` when the user runs the default `Octo` command.
When turned off the behavior of `Octo` should be the same. When enabled it should run `Octo actions`
I've set the default behavior of it to be off but maybe it should just be on by default and just remove the error message when no action is provided? 🤔
=> feature: Show builtin actions when no action is provided

lua/octo/ui/writers.lua
The state colors were not being loaded because of this string concatenation.
Because it is not documented this way, I took the initial approach of simply removing the concatenation, however in order to not break existing configurations which have figured this out, perhaps we should add `Float` to the names here instead, and update the documentation accordingly:
https://github.com/pwntester/octo.nvim/blob/2d2769ff80a82a0da24dcf636ae146f3ed5d7ae5/lua/octo/ui/colors.lua#L113-L121
WDYT?
fixes #405
=> Fix state highlighting

lua/octo/commands.lua, lua/octo/utils.lua
This commit changes the `repo view` command to fetch the cwd git remote-origin when no repository argument is provided. If its not in a git folder then it will just log an error instead.
Fixes #413 
Check cwd is a git folder -> Attempt to fetch origin url -> Pull repository name and pass to edit octo buffer
Run `Octo repo view` in a folder that has a remote-origin set
=> fix: Use cwd's origin url on `Octo repo view` when no argument is passed

lua/octo/pickers/fzf-lua/pickers/actions.lua
This commit fixes a bug where the fzf-lua actions picker references an unknown opt table and uses a default `Action` string as the picker title.
Fixes #415 
Removed an uninitialized opt table reference
Switch to fzf-lua as a picker and run `Octo actions`
=> fix: Use default title for fzf-lua actions picker

lua/octo/navigation.lua
When plugin is configured to use Github Enterprise instance there is an issue related to opening PR/repo/issue from current buffer. It's unnecessary to use a `repo` argument to `gh` command in this case, so we can skip it.
NONE
I just removed `-R` argument from the call of `gh` command
=> fix: error opening current issue/pr/repo in browser when using Github Enterprise

lua/octo/ui/colors.lua
Closes #424 
Adjusting the `get_background_color_of_highlight_group` function to support cleared highlight groups.
- Falling back to `highlight_group_normal.foreground` is both confusing and makes it impossible to overwrite the default background value to a null value. So I've removed it.
- Removed the fallback else if background color isn't defined. In my case, I don't want there to be a background color so I'm clearing the `OctoEditable` highlight but the previous logic would still add a color back.
Resolves https://github.com/pwntester/octo.nvim/discussions/424
Please let me know if the black background was intentional. And if so, what I would need to do to allow the `get_background_color_of_highlight_group` to return a cleared value so I can get a transparent UI.
=> Improve background color

lua/octo/utils.lua
It fixes missing space in file panel.
NONE
Added the missing space.
1. Start a review
2. Mark a file as viewed
3. Check the mark looks good
=> fix: add space after the viewed icon

lua/octo/commands.lua, lua/octo/navigation.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/ui/colors.lua
the function `M.load_buffer` accepts the buffer number but the reload function passes in several arguments, causing the `Octo pr reload` always to fail 
https://github.com/pwntester/octo.nvim/blob/bd53dee3ab1bf13882e3e5013f355d802b0a76ad/lua/octo/init.lua#L64
=> Fix wrong argument in load buffer function

lua/octo/commands.lua
Fixes the issue where the PR title doesn't get populated on create.
Fixes #444 
If the last commit doesn't have body, the logic skips setting the title. So I adjusted it to always set the title if the commit has a description (even without a body).
1. Create a commit without a body (just a title)
2. Create a PR with Octo
3. The "Enter title:" input will be populated with the commit title
=> fix: setting title for pr create

lua/octo/pickers/fzf-lua/pickers/utils.lua
Just an incorrect index into table.
Fixes https://github.com/ibhagwan/fzf-lua/issues/920
Looked at fzf-lua's code
See the link above: try to add/remove a label with fzf-lua picker.
=> fix: label coloring

README.md, doc/octo.txt, lua/octo/commands.lua
This PR adds an `Octo pr draft` command to send a "ready for review" PR back to draft status.
Fixes #451 .
I copied the `pr ready` command related code, and added the `--undo` switch as specified in the `gh` documentation.
Open a PR with `Octo pr open`, and issue `Octo pr draft`. It will be sent back to draft.
=> feat: add pr draft command to send a ready PR back to draft

README.md, lua/octo/config.lua, lua/octo/pickers/fzf-lua/pickers/fzf_actions.lua, lua/octo/pickers/fzf-lua/pickers/prs.lua, lua/octo/pickers/fzf-lua/pickers/utils.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/utils.lua, lua/tests/plenary/utils_spec.lua
Adds config options to change the telescope or fzf-lua mappings.
Fixes #447
I added the the config options and used them in the telescope and fzf-lua picker code. I added a util, along with spec tests, that converts vim style mappings to fzf ones.
1. Change `pwntester/octo.nvim` to `benelan/octo.nvim` in your Neovim plugin config
2. Add the following to your Octo config
```lua
picker_config = {
mappings = {
open_in_browser = { lhs = "<M-b>", desc = "open issue in browser" },
copy_url = { lhs = "<M-y>", desc = "copy url to system clipboard" },
checkout_pr = { lhs = "<M-o>", desc = "checkout pull request" },
merge_pr = { lhs = "<M-r>", desc = "merge pull request" },
},
},
```
3. Open an Octo telescope or fzf-lua picker, e.g. `Octo pr list`
4. Verify that the mappings are triggered with alt …
=> feat(picker): add config options for changing mappings

lua/octo/ui/colors.lua
This PR fixes the wrong bubble background colors, which should be introduced in https://github.com/pwntester/octo.nvim/pull/433
Possibly fixes https://github.com/pwntester/octo.nvim/issues/412
Looks like `vim.api.nvim_get_hl` returns a different structure that contains `{ bg, fg }` instead of `{ background, foreground }`, this PR fixes the property names.
- Before this PR:
- After this PR:
=> Fix wrong bubble background colors

lua/octo/commands.lua
When resolving threads via `Octo thread [un]resolve` the virtual text of the thread should be updated with the new resolved-state. Currently the text only gets cleared due to an oversight.
Fixes #362 
Added a field, which was needed since a feature commit
Tested it within the timeline (`Octo pr list`)  aswell as within the review mode (`Octo review start`). Just resolved and unresolved some threads.
Fwiw this seems to be introduced with the commit 50704c5071e9dd4a5643f55403f146b2bbe710bc. With this commit the wrapper around writing this specific virtual_text now expects a `commit` field. 
I have added a for loop to gather the commit sha of the actual thread from the response from github. If there is an easier way, Im happy to change it. 
Sidenote: the duplicated code between …
=> Fix thread header becoming invisible after toggling resolved-state

lua/octo/gh/init.lua
This commit fixes an issue with the newer version of the gh cli tool where they updated the stdout message.
Reference: https://github.com/cli/cli/commit/e806664ef736a1cba373155842112831d094b91f
Closes: #466
=> fix: Adjust get_user_name regex to match updates to the cli

lua/octo/commands.lua, lua/octo/config.lua, lua/octo/gh/init.lua, lua/octo/model/octo-buffer.lua, lua/octo/picker.lua, lua/octo/pickers/fzf-lua/pickers/fzf_actions.lua, lua/octo/pickers/fzf-lua/pickers/issues.lua, lua/octo/pickers/fzf-lua/pickers/prs.lua, lua/octo/pickers/fzf-lua/previewers.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/reviews/file-entry.lua, lua/octo/reviews/file-panel.lua, lua/octo/reviews/init.lua, lua/octo/reviews/renderer.lua, lua/octo/ui/bubbles.lua, lua/octo/ui/colors.lua, lua/octo/ui/signs.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua, lua/tests/octo/config_spec.lua, lua/tests/plenary/config_spec.lua
This commit reworks the config setup structure and adds Config typing, validations and tests. On config setup the user's configuration will be validated against. Any type errors raised by invalid settings will result in a user-friendly error message being shown to the user. I've lifted a majority of it from another plugin (neogit) that I've contributed to before as It seems to work well.
I've run into issues in the past where my configuration was out of date and once I updated I'd have to track down the change and apply it. With this it should be a lot more easier to see the config issue.
This also adds much needed typing annotations and configuration tests to make it easier to detect regressions/unintended changes. I still need to add validations for the mappings but this is essentially …
=> feat: Rework configuration setup to add validation

lua/octo/gh/init.lua
This makes sure we have some scope string, even if the parsed output is nil.
Fixes https://github.com/pwntester/octo.nvim/issues/480
Assign a default to the match.
Get a `gh` version that doesn't output the scopes properly, or according to how we want to parse them.
None
=> fix: nil scopes match

doc/octo.txt
The docs to suppress project v2 warnings have a typo and should be `projects_v2` instead of `project_v2`.
Not a GH issue.
Updated docs
Compare with config: https://github.com/stickperson/octo.nvim/blob/2d3b4c1e3ad5a75968476c0f2e75ef5476346d37/lua/octo/config.lua#L107-L109
=> fix typo in docs to suppress projects v2 warning

README.md, lua/octo/commands.lua, lua/octo/config.lua, lua/tests/plenary/config_spec.lua
This commit adds a new option `default_merge_method`, which can be used to define the default merge method for the `Octo pr merge` command.
Until now the `Octo pr merge` was always using `commit` when no argument was defined. This can now be customized by the user. A user can select between `commit`, `rebase` and `squash`. If another string is provided it will fallback to `commit`.
This is especially useful (at least for me 😅) when the `enable_builtin` option is enabled and the merge command is selected via Telescope where it isn't possible to provide the merge method.
NONE
- I'm not very familiar with Lua and writing Neovim plugins, so maybe this PR is completely shit
- If this isn't a feature you want to add, feel free to just close the PR (sry I was a bit lazy with creating an GitHub …
=> feat: Add default merge method

README.md
The config option in the README is not named properly.
It currently says:
```
suppress_missing_scope = {
project_v2 = true,
}
```
and yet we can clearly see that the expected option is `projects_v2`:
lua/octo/gh/init.lua:
```lua
elseif not config.values.suppress_missing_scope.projects_v2 then
require("octo.utils").info "Cannot request projects v2, missing scope 'read:project'"
end
```
Doesn't fix any outstanding issues that I am aware of.
I fixed the typo by reading the source code handling the option and reading the README.
The suppression of this warning will actually work (if you use the non-typo'd version of the config present in the README).
RELATED: https://github.com/pwntester/octo.nvim/commit/2d3b4c1e3ad5a75968476c0f2e75ef5476346d37
=> fix typo in docs regarding projects_v2 config

README.md, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/mappings.lua, lua/octo/reviews/init.lua
The process of opening a pull-request and starting a review was a little disconnected, as we had keymaps to almost everything we can do with a pull-request, except for starting a review.
https://github.com/pwntester/octo.nvim/assets/4634613/68458e0b-d791-4ab4-b568-3ef8532142ac
I followed the project standard and created named mappings that mirror the configuration keys and added them to:
* Pull request buffer (`pull_reqest`)
* The diff-view of the Review (`review_diff`)
* The review pane (`file_pane`)
The new commands are:
| Command | Binding |
|--------|--------|
| `review_start` | `<leader>vs` |
| `review_resume` | `<leader>vr` |
| `submit_review` | `<leader>vs` | 
| `discard_review` | `<leader>vd` |
1. Open a Pull-Request 
2. press `<leader>vs` to start a review
3. press `Ctrl+c` to …
=> Add keymaps for start, resume, submit and discard Reviews

README.md, lua/octo/config.lua, lua/octo/gh/init.lua, lua/octo/init.lua
This allows defining the path of the `gh` binary
Following the convention set out by other configurable values I simply added in `gh_cmd` with a default of `"gh"`.
For all uses of `command = "gh"` I changed it to `command = config.values.gh_cmd`
Setting the `gh_cmd` value in setup to the path of a working Github CLI binary
If this isn't something you are interested in including that is all good. I made the changes so I could use this plugin with my neovim configuration and thought it may come in handy to others as well 😄
=> Allowing configuration of `gh` binary path

README.md
Fixes typo in docs, wherein the `picker` and `picker_config` configuration keys appear twice in the list of config options.
Fixes #509
Removed the duplicate entries that had less complete information, compared to the other set of entries.
N/A
N/A
=> doc: remove duplicate options from readme

lua/octo/navigation.lua
Flag `-R` does not exist with `gh repo view`
Fixes #511 
Removed flag
1. Octo repo view
2. Octo repo browser
=> fix: improper gh cli flag for repo browser

lua/octo/pickers/fzf-lua/pickers/search.lua
Defines `formatted_items` so items in the `search` commands can be selected without an error.
Fixes https://github.com/pwntester/octo.nvim/issues/503
Defined the items each time contents.
Try the repro steps in https://github.com/pwntester/octo.nvim/issues/503.
In each case make sure there is no error:
=> fix: formatted items in search was undefined

lua/octo/ui/writers.lua
When a repo doesn't have a default branch name (i.e. a totally empty repo) then Octo gives an error when trying to view that repo.
This fixes that. Additionally, because when using the fzf-lua picker since the repo is previewed the error can show up when that repository is highlighted.
Fixes https://github.com/pwntester/octo.nvim/issues/519
Check for the default branch ref and if it's `vim.NIL` the name just becomes nil. This will prevent displaying the name as well as fetching the README from the default branch.
Make a repo on Github and don't configure anything (no README, no .gitignore, no license file, etc.), then run `:Octo repo view you/your-repo`. Make sure there is no error as seen in #519 
N/A
=> fix: lack of default branch name causes repo display issue

lua/octo/reviews/file-entry.lua
Fixes a bug where attempting to review a specific commit fails if the comment contains comments due to us attempting to add an extmark to a line that is out of bounds, which results in the following error:
```
Error executing vim.schedule lua callback: ...hare/nvim/lazy/octo.nvim/lua/octo/reviews/file-entry.lua:394: Invalid 'line': out of range
[C]: in function 'nvim_buf_set_extmark'
...hare/nvim/lazy/octo.nvim/lua/octo/reviews/file-entry.lua:394: in function 'place_signs'
...hare/nvim/lazy/octo.nvim/lua/octo/reviews/file-entry.lua:266: in function 'load_buffers'
...al/share/nvim/lazy/octo.nvim/lua/octo/reviews/layout.lua:116: in function 'set_file'
...al/share/nvim/lazy/octo.nvim/lua/octo/reviews/layout.lua:136: in function 'update_files' …
```
=> fix(file-entry): ignore possible extmark out of bounds error

lua/octo/autocmds.lua, lua/octo/init.lua
When Octo loads on `BufReadCmd octo://*`, it doesn't pass the correct buffer and can
as such eventually load in a different buffer
Simply pass the event buffer and wrap the result callback in a `nvim_buf_call` to ensure we render in the correctbuffer
Add `blank` to `sessionoptions`.
Make a split with one normal file and with an octo buffer.
Make the normal file the current window.
Make a session
Exit Neovim
Open NEovim
Restore Session
The octo buffer will load in the correct window,
Without this PR, it would load in the file window.
=> fix: load octo in the correct buffer

README.md, lua/octo/autocmds.lua, lua/octo/config.lua, lua/octo/folds.lua, lua/octo/init.lua, lua/octo/model/octo-buffer.lua, lua/octo/reviews/thread-panel.lua, lua/octo/ui/colors.lua, lua/octo/ui/signs.lua, lua/octo/ui/statuscolumn.lua, lua/octo/ui/writers.lua
This PR fixes both issues/features as described in #80:
* use `statuscolumn` on Neovim >= 0.9 for rendering comment signs, so that they render correctly when wrapping
* use `foldtext` on Neovim >= 0.10 for better rendering of folded comments/threads/...
Fixes #80
I implemented both a statuscolumn and foldtext.
See the two different commits.
In Neovim 0.10, check the features described
In the screenshot you can see comment markers from a wrapped comment.
And what a folded thread looks like (lighter background)
Edit: I seem to have included the code from my other PR as well :)
=> feat: comment statuscolumn & foldtext

.pre-commit-config.yaml
This adds pre-commit linting hook to the project. It is the same one used in the GitHub action.
=> Add stylua pre-commit

lua/octo/commands.lua, lua/octo/utils.lua
related to #584. 
The creation of the comments were happening in local time but were being stored in UTC.
Also worked through the `date_format` function to make sure that the date difference is
being calculated correctly.
=> Fix human readable time differences

lua/octo/gh/graphql.lua, lua/octo/reviews/init.lua
This reverts commit b4923dc97555c64236c4535b2adf75c74c00caca since it caused #592
=> Revert "fix: escape new line in graphql pr review queries"

README.md, lua/octo/config.lua, lua/octo/gh/graphql.lua, lua/octo/pickers/telescope/provider.lua
Use repo's assignable / mentionable users to populate finder instead of general GitHub search.
TODO:
Closes #423 
Pull out the finder creation logic
Use `Octo assignee add` or `Octo reviewer add` to see the new behavior.
=> Use repo assignable / mentionable users in finder

README.md, lua/octo/autocmds.lua, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/reviews/init.lua, lua/octo/reviews/thread-panel.lua
Add a config option to disable the auto thread opening on cursor move during review
Due to how diff works in nvim, I found it very hard to focus whenever there was more than one or two comments on a file
Fixes #536
- Add the config option
- Create a command to call show review thread so that users can bind it
- When the config option is set,
- do not create the cursor move autocmd that calls show review thread
- create an local buffer keybind to close the comment buffer on q since it no longer auto closes when going back to diff
Octo config
```lua
opts = {
reviews = {
auto_show_threads = false,
},
},
```
Open a pr review
- Go on a thread, call `<CMD>Octo review thread<CR>`
or
- Create a comment using `<CMD>Octo comment add<CR>`
See buffer open, and press q to close it
=> feat: allow disabling auto review thread opening

lua/octo/utils.lua
the automatic repository finding (when none passed as args) wouldn't work when the return of `git remote -v` had a trailing '/'. this is reproducible by adding a trailing '/' when cloning a repository
parser would split the lines with '/' as a delimiter. the trailing '/' made the result be an array of length 4 which wasn't considered.
Fixes #605 
added condition for when the split segments has a length of 4.
```bash
git clone https://github.com/pwntester/octo.nvim/ && cd octo.nvim && nvim -c 'Octo issue list'
```
additional checking that `segment[4] == nil` could be added to ensure this change fixes only this edge case
the opposite approach could be made and use `if #segments > 2` so it becomes the default behavior for more edge cases
=> fix(repo parsing): considers cases where git repo has a trailing /

doc/octo.txt, lua/octo/commands.lua, lua/octo/reviews/init.lua
Automatically resume a pr or open a new one depending on whether one is already in progress
Helps #601
Add a new `start_or_resume` function, and bind it to `:Octo review`
Go to a pr
- With no review started, use the `:Octo review` command
- See review started and diff opened
- Close review and open same pr (or any pr with a review pending), use the `:Octo review` command
- See review resumed and diff opened
=> feat: start or resume a review with `:Octo review` command

README.md, lua/octo/commands.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/utils.lua
Adds `issue develop` command. 
If on issue buffer, the current issue is checked out and the branch is created.
If not, then a picker is shown to select an issue to checkout and create a branch.
NOTE: Only implemented for the telescope picker
Related to #443
=> Add `Octo issue develop` command

lua/octo/navigation.lua
Similar fix to https://github.com/pwntester/octo.nvim/issues/631, but the `Octo repo browser` command fails unless you are viewing an Octo buffer. These changes just enable this command to work when one is not opened.
Added handling within our `if not buffer` block so that `octo` tries opening the remote repo url using the `utils.get_remote_name` function.
- `cd` to a local directory that is not a `git` repository:
- open `neovim`
- run `:Octo repo browser`
- verify you see the "No remote repository found" message
- `cd` to a local `git` repository that is tracking a remote GitHub repository:
- open `neovim`
- run `:Octo repo browser`
- verify you see the "No remote repository found" message
- `cd` to a local `git` repository that _is_ tracking a remote GitHub repository:
- open `neovim` …
=> open remote URL from any buffer w/ :Octo repo browser

lua/octo/commands.lua, lua/octo/utils.lua
This PR fixes the `:Octo repo url` command. It silently fails when an Octo buffer is not opened, but this command should not require one to get the remote url.
Closes https://github.com/pwntester/octo.nvim/issues/628
To fix, I've just used the utility functions `get_remote_host` and `get_remote_name` and concatenation to build out the remote url name, which can be used to get the remote url when an Octo buffer is/is not opened.
- `cd` to a local directory that is not a `git` repository:
- open `neovim`
- run `:Octo repo url`
- verify you see the "No remote repository found" message
- `cd` to a local `git` repository that is tracking a remote GitHub repository:
- open `neovim`
- run `:Octo repo url`
- verify you see the "No remote repository found" message
- `cd` to a local `git` …
=> fix the :Octo repo url command

lua/tests/minimal_init.vim, lua/tests/test_utils.lua
Fix [test error](https://github.com/pwntester/octo.nvim/actions/runs/11307537257/job/31449367731):
```
Error detected while processing /home/runner/work/octo.nvim/octo.nvim/lua/tests/minimal_init.vim:
line   13:
E5108: Error executing lua [string ":lua"]:2: Vim(luafile):E5112: Error while creating lua chunk: cannot open ./tests/test_utils.lua: No such file or directory
[C]: in function 'cmd'
[string ":lua"]:2: in main chunk
========================================
```
=> test: fix test utils import

lua/octo/pickers/fzf-lua/previewers.lua
Fzf-lua previewer didn't handle error when no matched result found.
Fix https://github.com/pwntester/octo.nvim/issues/611.
Do noting when no matched result found.
=> fix(fzf-lua): when no search result

lua/octo/gh/graphql.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
Using the state, isDraft, stateReason fields from the graphql API to determine the icon and color of the PR or Issue. This should be consistent with the github interface.
This works for `:Octo issue / pr list / search` and `:Octo search`
Related to #485
- Add state, isDraft, stateReason to the related graphql queries
- Determine the icon and color based on these fields
- Implement for all list and search commands
Run any of the affected commands and see that the icons will be colored based on the state of the PR or Issue.
This only effects telescope picker
=> Add colors based on Issue / PR state

lua/octo/commands.lua, lua/octo/pickers/telescope/provider.lua
`Octo pr search` lacks bindings for merge/checkout PR, one has to open it first.
NONE
I just pass extra `search_prs` param in `pr search` command  to `picker.search`.
run `Octo pr search` and observe that checkout/merge bindings work in telescope
see https://github.com/pwntester/octo.nvim/pull/635#issuecomment-2432220568
=> add merge/checkout bindings to pr search for telescope

lua/octo/autocmds.lua, lua/octo/commands.lua, lua/octo/init.lua
Both the `:Octo pr reload` and `:Octo issue reload` will keep the cursor location. There be an info message displayed when the buffer is reloaded.
The `load_buffer` function now accepts a table with bufnr and verbose keys. 
Closes #623
=> Keep cursor location while reloading

lua/octo/reviews/file-entry.lua
Displays "comment" in review buffer instead of "comments"
Fixes #648
Make a comment in your review and see that it's displayed as "1 comment" in diff
=> use "comment" over "comments" in review buffer

README.md
- There isn't a `Status column` subsection in the README.
- `Status column` is currently a broken link in the README's TOC (table of contents).
Fixes #655 
- I removed the broken link from the README
=> Remove 'Status Column' from README's TOC

lua/octo/ui/writers.lua
See extra space in PR > review title:
NONE
=> remove extra space from review author bubble

lua/octo/pickers/telescope/provider.lua
It may happen that `selection` is `nil`, which results in an error being logged.
This silently skips the failing function in such cases.
Run `Octo pr search` and fiddle around with filtering and navigation
=> fix(pickers/telescope): handle nil selection in open

lua/octo/utils.lua
Absolute and relative filesystem paths are also valid remote urls. Using them on a repo results in an error when listing PRs.
Set `host = nil` and `repo = url` when remote url starts with `/` or `.`.
```
$ git remote add foo ${HOME}/somepath
:Octo pr list
:Octo pr search
```
=> fix: handle local filesystem remotes

lua/octo/commands.lua
If an error is thrown during an action, an error is logged with the message `Incorrect action: $action`. This is the same error message as for actually missing commands.
This is confusing and adds friction for debugging.
Differentiate between missing and failing actions and log them differently.
=> differentiate between failing and missing actions in error message

README.md, lua/octo/utils.lua, lua/tests/plenary/utils_spec.lua
Some people may use "dynamic" remote hosts like `github.com-foo`, `github.com-bar`, etc. Having to additionally add each as an explicit `ssh_aliases` entry can become a chore.
Interpret keys in `ssh_alieses` configuration as [Lua patterns](https://lua.org/pil/20.1.html). This allows an alias like `github\.com-.*`.
=> feat: match patterns in ssh_aliases

lua/octo/gh/init.lua
Improves the error handling and user notifications when the user does not want to use Projects v2 by default, i.e., when not setting the `default_to_projects_v2` config option or setting it to `false`.
In the current code users see an unexpected error message about missing `gh` token scopes in two different scenarios:
1. They did not enable `default_to_projects_v2` and they do not have the `read:project` or the `project` scopes in their `gh` token
2.  They do have either the `read:project` or the `project` scope in their `gh` token but have not set the `default_to_projects_v2` or have set it to `false`.
In other words: They will always receive an error message if `default_to_projects_v2` is disabled.
They should only recive an error message if they enable `default_to_projects_v2` and do …
=> Fix #564: Improve error checking logic

lua/octo/gh/graphql.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
This adds the name in parenthesis to the list of users in various commands.
Helps with assigning people's whose logins are not the same as their names and you know name over username
=> Add name in user queries

README.md, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/utils.lua
- raises error when merging from picker failed (like `Octo pr merge` does)
- adds `default_delete_branch` setting which can be overridden with
`delete`/`nodelete` argument to `Octo pr merge`
- also applies all merge defaults when merging from picker
Fixes #657
1. Find PR which is not mergeable
2. Select it in `Octo pr search` for example (don't open)
3. Press "merge pr" binding (`<C-r>` by default)
4. See error message
=> merging from picker: raise error if failed and apply merge defaults

lua/octo/gh/graphql.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
Displays "Auto-merge" section for PR if it was enabled, it's nice to see if I need to merge PR or it's already scheduled for auto-merge.
NONE
Apply auto-merge to blocked PR with `gh pr merge --auto` and see this section.
=> display auto-merge in pr view

README.md, lua/octo/gh/graphql.lua, lua/octo/model/octo-buffer.lua, lua/octo/model/pull-request.lua, lua/octo/reviews/file-entry.lua, lua/octo/reviews/init.lua, lua/octo/utils.lua
Allow running `:Octo review` commands when not in an PR buffer to start/resume reviews for the currently checked out branch.
Helps #601
=> feat: allow entering review mode without being in an octo pr buffer

.github/workflows/lint.yml
Fixes failing stylua action check.
Set `version` field of stylua-action, in accordance with usage: https://github.com/JohnnyMorganz/stylua-action#usage.
Take a look at current commits in `master` and recently open PRs. They are failing the stylua action check. This PR is not failing that check.
I'm not sure if `latest` actually makes sense here. Just picked a working value.
=> chore(ci): set stylua action version

lua/octo/utils.lua
Fixes #608
I gave up on trying to troubleshoot async plenary, and switched to sync, this fixes the empty diff buffer for local mode that is quite hard to reproduce.
Since this is a local git command, and, impact should be minimal, and the only caller of this function waits for the job to be done anyway by calling vim.wait on a condition that is done by the callback
=> Use plenary sync job to get local file content

lua/octo/gh/graphql.lua, lua/octo/model/octo-buffer.lua, lua/octo/ui/colors.lua, lua/octo/ui/writers.lua
Title renaming events are now in the issues and pr buffers
Related to #680
Three steps: 
- Change to graphql query to get the title renaming events
- Add some parsing to render
- Add writer 
Can view in prs like this one or like #635 
Or in Issues like #680
=> Add missing title renaming event

lua/octo/gh/graphql.lua, lua/octo/pickers/telescope/provider.lua
The large amount of padding for `Octo search` is now gone when doing *repo specific* search queries.
```
:Octo search repo:microsoft/vscode label:bug # takes min of 6 and the digits from number of issues in the repo
:Octo search is:issue repo:pwntester/octo.nvim label:bug # takes min of 6 and the digits from number of issues in the repo
```
Same for non-repo specific queries
```
:Octo search is:issue label:bug
:Octo search -repo:pwntester/octo.nvim octo.nvim in:body
```
Added a second query to get the number of issues (and PRs) for the repo
Check out any of the examples above with the telescope picker
Only for the telescope picker
=> Smaller number padding for repo specific searches

lua/octo/commands.lua, lua/octo/gh/graphql.lua, lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua, lua/octo/pickers/fzf-lua/pickers/labels.lua, lua/octo/pickers/telescope/provider.lua
Allows user to allow multiselect for adding and removing labels
Related to #675
- Adapt the graphql command to pass list of labelIds
- Generalize telescope logic to grab multiple selection and check if non-empty
- Use callback on list of labels including list of single label
For telescope, use `<Tab>` to select multiple labels (while adding or removing) then press enter to confirm. If Tab is not pressed, then the behavior will be the same as before.
Telescope only. However, fzf had support before but the cb was changed to support batch label add.
=> Support label multiselection

lua/octo/utils.lua
See issue for full explanation
TL;DR: Using `use_local_fs` for branches with `/` in the name (e.g. `name/feature`) would cause Octo to think that the local branch never matched the PR branch. 
Fixes #699 
Instead of taking the first `/` after the remote, we concat all leftover entries in the table.
1. Create PR from branch with /
1. Checkout branch
1. `:Octo {PR URL}`
1. `:Octo review start`
=> [Fix #699] `use_local_fs` with slash in branch name

lua/octo/reviews/init.lua
Fixes #739
- replace vim.error with utils.error in review:discard and review:resume
`vim.error` call leftovers are being replaced with `utils.error` call to avoid the error
https://github.com/user-attachments/assets/41d0de39-9642-4959-b253-f139aa75c923
=> fix: replace vim.error with utils.error

lua/octo/gh/init.lua, lua/octo/reviews/init.lua
Wrapper function around gh.run in order to support parameterized queries. Also makes it more transparent what fields are being passed to the queries.
```lua
local lastest_issue_query = [[
query($owner: String!, $repo: String!, $num_issues: Int!) {
repository(owner: $owner, name: $repo) {
issues(last: $num_issues) {
nodes {
title
}
}
}
}
]]
local result = gh.graphql {
query = lastest_issue_query,
fields = {
owner = "pwntester",
repo = "octo.nvim",
num_issues = 5,
}, 
jq = ".data.repository.issues.nodes | map(.title)",
opts = {
mode = "sync",
}
}
```
Wrapper function around gh.run and parsing of fields to support parameterized queries.
=> Wrapper to support parameterized queries

lua/octo/commands.lua, lua/octo/gh/graphql.lua, lua/octo/pickers/fzf-lua/provider.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/pickers/vim-clap/provider.lua, lua/octo/utils.lua
Adds commands for milestones: 
- create (new milestone)
- add (add a milestone to an Issue or PR)
- remove (remove a milestone from an Issue or PR)
- list (list all (open) milestones)
Closes #725
Closes #343
Add queries for the new commands and implement
Try out the 4 new commands
commands that rely on pickers will only work for the telescope picker
=> add Milestone commands

lua/octo/utils.lua
We were attempting to trim off the .git from the remote url to get the
remote repo name with owner. However, when the repo name ended with git,
that part of the repo name was trimmed off, e.g. cmp-git became cmp.
This properly escapes the `.` to only trim off `.git`.
=> fix: trim off .git from remote url properly

lua/octo/ui/writers.lua
When the actor and assignee are the same, the writer will say "self-assigned this"
Case in the writer for self-assigned
Look at issue that has that condition
=> Add self-assigned to UI

lua/octo/commands.lua
I wanted to create a pull request with octo, but for some reason there was a message displayed, that the current branch has no remote and if I wanted to push the current one. 
The reason was that the command pulls remote branches from the remote that takes precedence. 
That is the upstream repo. Therefore, the local branch of course does not exist in that remote.
Fixes #400
I changed the `pr create` command so that it first tries to get from the remote `origin` not according to the precedence.
This very PR was created with Octo :-)
=> fix: create pr with upstream remote now works

lua/octo/reviews/file-entry.lua
Fixes #776
Add a check in the `destroy` function in `lua/octo/reviews/file-entry.lua` to verify if the buffer id is valid before attempting to delete it.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/pwntester/octo.nvim/pull/777?shareId=76293ee0-5b35-43d2-ac7d-d5b734aceabf).
=> Fix buffer id error in TabClosed Autocommands

README.md, lua/octo/config.lua, lua/octo/mappings.lua
Add the command functions; resolve_thread() and unresolve_thread() to the mappings.lua to allow setting keymaps to resolve and unresolve threads.
fixes #780
The thread resolver is only accessible for `_G.octo_buffers`. Hence, not possible to add without refactoring for `review_diff` and `file_panel` further.
=> feat: Add default (un)resolve mappings to PR

lua/octo/gh/fragments.lua, lua/octo/gh/graphql.lua, lua/octo/gh/init.lua
This is a consolidation of queries to use GraphQL fragments
=> Refactor to fragments

lua/octo/commands.lua, lua/octo/gh/graphql.lua
Issues that were closed with NOT_PLANNED or DUPLICATE were not able to be reopened as a
specific mutation was required
Closes #723
Add GraphQL mutation and separate out in reopen case.
Close an issue with NOT_PLANNED status and reopen it.
=> use reopenIssue to support not_planned and duplicate

README.md
Fix the README example config which uses ; instead of ,
=> switch ; to , in README

lua/octo/utils.lua
Uses gh.run to capture the output and stderr in order to display error on failure
Closes #759
Use `:Octo pr checkout` from a PR buffer in different cases.
=> Catch stderr on pr checkout

lua/octo/commands.lua, lua/octo/pickers/telescope/provider.lua
Various telescope pickers can now take an arbitrary callback function to handle the selected item.
Example:
```lua
local picker = require "octo.picker"
local opts = {}
opts.cb = function(selected)
vim.notify(vim.inspect(selected))
end
-- picker.issues(opts)
-- picker.prs(opts)
picker.discussions(opts)
```
The default behavior is preserved if no callback is provided.
Closes #642
Create common selection callback function 
Try various commands like: 
`:Octo issue list`
`:Octo issue develop`
`:Octo pr list`
`:Octo discussion list`
Try the example code above to provide for custom callback function.
=> 642 abitrary selection callbacks for pickers

.graphqlrc
This file is used by graphql lsp server to provider completion and information from the GitHub schema
=> Add graphqlrc file

lua/octo/init.lua
fix: reloading an modifiable octo buffer may cause a runtime error
Fixes: #811
```
Error executing vim.schedule lua callback: ...hare/nvim/site/pack/deps/opt/octo.nvim/lua/octo/init.lua:111: Error executing lua: .
..hare/nvim/site/pack/deps/opt/octo.nvim/lua/octo/init.lua:119: Cursor position outside buffer
[C]: in function 'nvim_win_set_cursor'
...hare/nvim/site/pack/deps/opt/octo.nvim/lua/octo/init.lua:119: in function <...hare/nvim/site/pack/deps/opt/octo.nvim/lu
a/octo/init.lua:111>
[C]: in function 'nvim_buf_call'
...hare/nvim/site/pack/deps/opt/octo.nvim/lua/octo/init.lua:111: in function 'cb'
...hare/nvim/site/pack/deps/opt/octo.nvim/lua/octo/init.lua:150: in function 'cb'
...e/nvim/site/pack/deps/opt/octo.nvim/lua/octo/gh/init.lua:163: in function '' …
```
=> fix: reloading an modifiable octo buffer may cause a runtime error

lua/octo/gh/init.lua, lua/tests/plenary/gh_spec.lua
This adds a metatable to the octo.gh module which allows for building commands more closely to the CLI commands.
For instance, 
```lua
local print_response = function(stdout, stderr)
vim.print(stdout)
vim.print(stderr)
end
local opts = {
cb = print_response
}
-- gh auth status -a
gh.auth.status { 
a = true,
opts = opts,
}
-- gh issue list --json author,labels
gh.issue.list {
json = "author,labels",
opts = opts,
}
-- gh pr list --search "is:merged -label:no releasenotes"
gh.pr.list {
search = 'is:merged -label:"no releasenotes"',
opts = opts,
}
-- gh pr view 810 --json author,labels,title,url
gh.pr.view {
810, 
json = "author,labels,title,url",
opts = opts,
}
```
> [!NOTE]
>
> Anything in the `opts` table will be passed to the `run` function
> [!NOTE]
>
> There …
=> Create CLI command builder with metatable

lua/octo/commands.lua, lua/octo/utils.lua
Previous to this comment highlighting several lines and running the command "Octo comment add" would never result in a multi-line comment.
This is seemingly because as soon as you enter the command line with ':' Neovim is switched back into normal mode and the "v" and "." attributes to `vim.fn.line` no longer register for the line range.
Instead, we can use the explicit start and end marks for a selected range to capture the currently selected range despite being in normal mode at time of command run.
It is now possible to highlight several lines in a review and then call "Octo comment add" to create a multi-line comment.
=> fix: make comment ranges work

lua/octo/pickers/fzf-lua/previewers.lua
This PR fixes #784 
The latest version of fzf-lua has updated the api, update_title and update_scrollbar are now called update_previewer_title and update_previewer_scrollbar respectively.
=> fix: fzf-lua previwer (#784)

lua/octo/model/pull-request.lua
Fixes: #819
The original arguments to `gh api` for certain commands are problematic.
For instance:
```
@@ -85,13 +95,14 @@ end
function PullRequest:get_changed_files(callback)
local url = string.format("repos/%s/pulls/%d/files", self.repo, self.number)
gh.run {
-    args = { "api", "--paginate", url, "--jq", "." },
```
In the above arguments the returned results, if exceeds one pages, will be two separate JSON arrays. E.g. [{...}][{...}].
You cannot feed this directly to `vim.fn.jsondecode` since its not actually valid json, its two json arrays in a single string.
Luckily, `gh` includes the `--slurp` argument to the `api` command which works similiarly to `jq`'s slurp command, concating sequential arrays.
We can use this, with one catch.
The results of any API call with `--slurp` is "an …
=> fix: use --slurp with --paginate to concat pages into valid json

lua/octo/commands.lua, lua/octo/reviews/init.lua, lua/octo/utils.lua
This PR is in response to: https://github.com/pwntester/octo.nvim/pull/807#discussion_r1929894670
This is a follow to making line selections work via the command line.
The crux of the confusion with this is that entering the command line from any other mode then normal, exits that mode, and enters normal mode.
Octo was trying to determine a selected line range, retroactively, when adding review comments. However, this doesn't really work since if you highlight a line, then want to run the comment add command, you exit visual mode. All 'state' related to visual mode and visual line rages are greedy and never 'reset' to 0 when visual mode is exited.
The "right" way that Vim intends you to figure out if a user command is being ran with a visual selection is by using the options dictionary …
=> fix: use user command lines ranges

lua/octo/reviews/file-entry.lua
When one side of the file is empty `return #self.left_lines > 0 and #self.right_lines > 0` will always be false. Thus `is_ready_to_render` will never be true. 
Fixes https://github.com/pwntester/octo.nvim/issues/817
=> Fix fetch timeout for newly added files

lua/octo/commands.lua, lua/octo/pickers/fzf-lua/pickers/prs.lua
When not in a Octo buffer, the command will use the PR picker to select a PR to checkout.
https://github.com/user-attachments/assets/422fa43e-5c25-40d4-ab01-64fbbe54b121
Very easy following #803
1. Open a non-Octo buffer
2. Run `:Octo pr checkout`
Only works for telescope
=> `Octo pr checkout` uses picker when not in Octo buffer

lua/octo/gh/init.lua
There is some instances where you can't checkout into a PR using GH PR checkout and We need to attach SSH_AUTH_SOCK to the gh initializer variables.
https://github.com/pwntester/octo.nvim/issues/831
=> Fix gh pr checkout by added the SSH_AUTH_SOCK env variable

README.md, lua/octo/reviews/file-panel.lua, lua/octo/ui/colors.lua
- Remove nocursorline because I find it very hard to spot my cursor in the review file panel, and add a more visible highlight to the selected entry
- Add hl group for selected entry in file panel
- Update readme list of hl groups
- Make sure we dont override user defined groups
I took inspiration from diffview, where it looks like this:
[Diffview](https://github.com/sindrets/diffview.nvim/blob/4516612fe98ff56ae0415a259ff6361a89419b0a/lua/diffview/hl.lua#L444) uses the `Type` native (?) hl group and it looked nice on my config, so I went with it.
I'm a bit of a dummy in terms of hl groups, let me know if we can do this better.
=> feat: improve visibility of selected entry in review file panel

lua/octo/reviews/file-entry.lua
Error was
```lua
Error executing vim.schedule lua callback: ...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:457: Failed to rename buffer
[C]: in function 'nvim_buf_set_name'
...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:457: in function '_create_buffer'
...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:273: in function 'load_buffers'
...ume/neovim-plugins/octo.nvim/lua/octo/reviews/layout.lua:123: in function 'set_current_file'
...ume/neovim-plugins/octo.nvim/lua/octo/reviews/layout.lua:145: in function 'update_files'
...laume/neovim-plugins/octo.nvim/lua/octo/reviews/init.lua:149: in function 'set_files_and_select_first'
...laume/neovim-plugins/octo.nvim/lua/octo/reviews/init.lua:193: in function 'callback' …
```
=> feat: fix error when trying to open a review while it is already opened

lua/octo/ui/writers.lua, lua/octo/utils.lua, lua/tests/plenary/utils_spec.lua
This change fixes the issue where the hyphen in the ssh_aliases replacement is not escaped. This causes the replacement to fail when the alias contains a hyphen.
The second change is related to issue #838, where the check for nil values are not working as expected. I have added a check for nil to author.user.
Fixes #836
Fixes #838
In parse_remote_url function, I have added a `%` before the hyphen in the ssh_aliases replacement.
In write_commit_event function, I have added a check for nil to author.user.
Test with an ssh alias that contains a hyphen, for example github.com-work
Test with a nil value for author.user
Little changes
=> fix: Escape hyphen in ssh_aliases and check for nil in author.user 

lua/octo/reviews/init.lua, lua/octo/utils.lua
Fixes: #828
When working in a mulit-remote pull requests may come from separate repositories.
Octo currently lets you list and view PRs from a configurable repository.
However, when it comes to checking out a review branch, it only looks at the current default repository via `gh cli`.
This change simply provides the PR's repository string to `gh pr checkout` command so non-default repository branches can be checked out as well.
Prior to this commit if you did something like `Octo pr edit 1234 owner/repo-b` where `repo-b` is not the default repository and tried to start a review, the PR branch would not be checked out, since its in the non-default repository.
=> fix: allow pr checkout from non-default repository

lua/octo/utils.lua
Docs only change. 
Seems like arguments for pr.edit and pr.issue were backwards. 
---
At some point the documentation for editing and issue and a pr drafted
from the code.
Update `get_repo_number_from_varargs` to reflect the documentation.
The documentation says `Octo pr [number] {repo}`
However, the code expected `Octo pr {repo} [number]`.
Fix this confusion by conforming to the documentation.
=> fix: fix 'edit' actions documented arguments

lua/octo/pickers/fzf-lua/entry_maker.lua, lua/octo/pickers/fzf-lua/pickers/utils.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
This is an alternative to #842
#826 changed the order of parameters of the `:Octo` command to be inline with the documentation. However, the order of the parameters used by the `fzf-lua` picker wasn't changed
Fixes #841 because of a regression introduced in #826
Change the parameter order just like on #826
`:Octo pr list` and choosing a PR while using `fzf-lua`  or `telescope` as picker will no longer result in errors
=> fix: follow parameter order change from #826

lua/octo/commands.lua, lua/octo/gh/graphql.lua, lua/octo/init.lua, lua/octo/model/octo-buffer.lua, lua/octo/model/pull-request.lua, lua/octo/navigation.lua, lua/octo/pickers/fzf-lua/entry_maker.lua, lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua, lua/octo/pickers/fzf-lua/pickers/assignees.lua, lua/octo/pickers/fzf-lua/pickers/changed_files.lua, lua/octo/pickers/fzf-lua/pickers/commits.lua, lua/octo/pickers/fzf-lua/pickers/fzf_actions.lua, lua/octo/pickers/fzf-lua/pickers/issues.lua, lua/octo/pickers/fzf-lua/pickers/labels.lua, lua/octo/pickers/fzf-lua/pickers/project_columns.lua, lua/octo/pickers/fzf-lua/pickers/project_columns_v2.lua, lua/octo/pickers/fzf-lua/pickers/prs.lua, lua/octo/pickers/fzf-lua/pickers/repos.lua, lua/octo/pickers/fzf-lua/pickers/review_commits.lua, lua/octo/pickers/fzf-lua/pickers/search.lua, lua/octo/pickers/fzf-lua/pickers/utils.lua, lua/octo/pickers/fzf-lua/previewers.lua, lua/octo/pickers/telescope/previewers.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/reviews/init.lua, lua/octo/ui/window.lua, lua/octo/utils.lua
- Updates type annotations to make it easier to work with the codebase
- Simplifies the logic of some small functions
- uses `vim.json.encode/decode` instead of `vim.fn.json_encode/decode`
- Adds better error messages to `repo`/`number` parsing to make it easier to catch regressions like #841 
NONE
- I checked the code to manually infer better type annotations for functions signatures.
The tests should still pass after the small refactors
=> Update type annotations, minor refactors, better error messages

lua/octo/ui/writers.lua
When another item is referenced, there will be a timeline item without information. This imposes a catch to not error out
when the item doesn't have an actor
=> fix: handle reference timeline event without actor

lua/octo/reviews/file-entry.lua
Fixes a lua error that happened this way
1. Open review
2. Close review
3. Delete null buffer (for example using `<cmd>%bd!|e#|bd!#<cr>`)
4. Open review
5. See this error
```lua
Error executing vim.schedule lua callback: ...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:492: Invalid buffer id: 6
[C]: in function 'nvim_win_set_buf'
...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:492: in function 'load_null_buffer'
...neovim-plugins/octo.nvim/lua/octo/reviews/file-entry.lua:485: in function 'load_null_buffers'
...ume/neovim-plugins/octo.nvim/lua/octo/reviews/layout.lua:247: in function 'file_safeguard'
...ume/neovim-plugins/octo.nvim/lua/octo/reviews/layout.lua:57: in function 'open'
...laume/neovim-plugins/octo.nvim/lua/octo/reviews/init.lua:190: in …
```
=> fix: properly check for null buffer loaded state on review open

lua/octo/autocmds.lua, lua/octo/commands.lua, lua/octo/mappings.lua, lua/octo/model/octo-buffer.lua, lua/octo/reviews/file-entry.lua, lua/octo/reviews/init.lua, lua/octo/reviews/thread-panel.lua, lua/octo/reviews/thread.lua
Fix error `gh: Could not resolve to a node with the global id of '-1'` when creating a comment from a thread buffer that was just used to create a new thread without closing it first
- Improved review typing
- Improved behavior of `Octo comment add` by ensuring the thread buffer was visible, and therefore that existing comment had been loaded, BEFORE trying to create a new comment
- Fixed the error of creating a new comment in a fresh thread, which was caused by the octo-buffer thread metadata not being updated with ids of created thread after the gh api
- Open a review
- On a line without a comment, run `Octo comment add`
- Save a new comment
- Re-run `Octo comment add` to add a reply to the comment you just created
- See the comment being registered without error, when the error `gh: …
=> Improve buffer behavior after thread creation

README.md, lua/octo/config.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
This allows the user to choose between all notifications and notifications for the current repository only.
The default is all notifications which is the current behavior.
1. Add configuration option
2. Use configuration option in the notification picker to toggle between the repo specific notifications and all notifications
Use `:Octo notification list` with configuration before and after
Only for the telescope picker as that is only one with notifications implemented
=> Feat: repo specific notifications

lua/octo/commands.lua, lua/octo/pickers/telescope/provider.lua
This change allows user to also pass a repo to the notification list command. 
`:Octo notification list pwntester/octo.nvim` would subset to any of the notifications from the repo `pwntester/octo.nvim`
This still respects the config.notification.current_repo_only configuration setting.
It allow for users with this configuration to use the picker programatically as well: 
```lua
local picker = require "octo.picker"
local opts = {
repo = "pwntester/octo.nvim",
}
picker.notification(opts)
```
> [!NOTE]
> 
> Using `:Octo notification` directly will have all notifications regardless of user configuration.
Move the repo logic outside of the picker and into the command.lua file
=> Pass repo to notification picker

README.md, lua/octo/config.lua, lua/octo/pickers/snacks/provider.lua
WIP adding snacks picker support 
Closes #809 
Just a draft for now but will add more support
Issues:
PRs:
=> feat: add snacks picker support for issues, prs, and notifications

.github/workflows/tests.yml
The README says that the latest version supported is v0.10.0 which didn't match which version is being tested in the CI/CD
Overall, testing with the later version of nvim might be a good idea. Maybe a matrix of version (old and new) can be tested in the CI/CD
What are the thoughts on this and which information is accurate?
Closes #770
=> test for nvim v0.10.0 in action

doc/octo.txt, lua/octo/commands.lua, lua/octo/config.lua, lua/octo/constants.lua, lua/octo/date.lua, lua/octo/model/octo-buffer.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/reviews/thread-panel.lua, lua/octo/ui/bubbles.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
When I was going through snacks, I found out there were typos everywhere. SO I just fixed them. Thats all. And used stylua to format.
NONE
Using typos cli, I found all typos, then fixed them one by one.
Well, look through diff.
=> fix(typos,indent): indent files with stylua and fix typos

lua/octo/pickers/fzf-lua/previewers.lua
`entry_str` don't need to be checked as empty string when nothing selected, since it's send as `nil` and avoided by:
https://github.com/ibhagwan/fzf-lua/blob/f8ccd73a7a3a0c9adae935441f85e83d5a989efd/lua/fzf-lua/previewer/builtin.lua#L355
Related: https://github.com/ibhagwan/fzf-lua/pull/1829
=> fix(fzf): upstream change "" to nil when no selected

lua/octo/gh/init.lua
Use with any function that uses gh.run
```lua
--- gh.run itself
local args = ...
local success_case = function(output)
vim.print(output)
end
gh.run {
args = args,
cb = gh.create_callback { success = success_case }
}
--- Any GitHub CLI command
local cb = gh.create_callback()
gh.pr.list { opts = { cb = cb } }
--- Any GitHub GraphQL query
local query = [[
query {
viewer {
login
}
}
]]
local success = function(login)
vim.notify("Hello, " .. login)
end
local cb = gh.create_callback { success = success }
gh.api.graphql { 
query = query, 
jq = ".data.viewer.login",
opts = {
cb = cb,
}
}
```
Closes #764
=> add a callback helper function

lua/octo/commands.lua, lua/octo/pickers/fzf-lua/pickers/assigned_labels.lua, lua/octo/pickers/fzf-lua/pickers/labels.lua, lua/octo/pickers/telescope/provider.lua
This allows for some more flexibility
For instance: 
```lua 
local picker = require "octo.picker"
picker.labels {
cb = function(labels)
vim.notify("The selected labels are: " .. vim.inspect(labels))
end
}
```
> [!IMPORTANT]
>
> This will only affect those that are using the pickers directly
TODO: 
Any thoughts on this?
=> allow for arbitrary callback in label pickers

lua/octo/gh/init.lua
Convenience wrapper around the REST API
```lua
local opts = { cb = gh.create_callback() }
gh.api { -- or gh.api.get
"/notifications",
opts = opts,
}
```
This would be the same as `gh api /notifications` with the CLI
Other available methods are: 
- `gh.api.post`
- `gh.api.patch`
- `gh.api.delete`
User can still specify the method if `gh.api` is used, e.g. `gh.api { "/notifications", method = "GET" }`
Closes #751
=> add REST API functions and metatable for get

lua/octo/commands.lua
Bit odd. The std_err seems to be returned regardless of the success of the command.
=> Use info only on pr ready command success

lua/octo/gh/init.lua
The function `gh.run` didn't allow for using the subcommands of GitHub CLI's `run` (Dynamic subcommands from #810)
This change allows for both. For example, `gh.run { args = { "pr", "list" } }` is backwards compatible. 
But `gh.run.list {}`, `gh.run.view { number }`, etc is now also possible.
=> allow for gh run commands as well as previous run function

lua/octo/gh/init.lua, lua/octo/pickers/telescope/provider.lua
Deprecate `gh.graphql`. Use `gh.api.graphql` instead
=> Favor gh.api.graphql and deprecate gh.graphql

lua/octo/gh/init.lua, lua/tests/plenary/gh_spec.lua
This allows use of graphql API to be a bit closer to the CLI
For instance, `gh api graphql -f query=<query> -F login=<login> -F repo=<repo>` is :
```lua
gh.api.graphql {
f = { query = query },  
F = { login = login, repo = repo }, 
}
```
The previous behavior still exists: 
```lua
gh.api.graphql {
query = query, 
fields = { login = login, repo = repo },
}
```
=> Make graphql closer to cli

lua/octo/gh/init.lua, lua/tests/plenary/gh_spec.lua
Closes #821
Use the `format` parameter to format a templated endpoint string
```lua
local endpoint = "/repos/{owner}/{repo}/issues/{issue_number}"
local opts = { cb = gh.create_callback {} }
gh.api.get { 
endpoint, 
format = { owner = "pwntester", repo = "octo.nvim", issue_number = 1 },
jq = "{ title, body, author: .user.login }",
opts = opts,
}
```
However, the `format` parameter is not required. If it is not provided, the endpoint string is used as is (current behavior).
```lua
local endpoint = "/repos/pwntester/octo.nvim/issues/1"
local opts = { cb = gh.create_callback {} }
gh.api.get { 
endpoint, 
jq = "{ title, body, author: .user.login }",
opts = opts,
}
```
CC: @ldelossa
=> Pass table to format templated endpoint

lua/octo/reviews/file-entry.lua
This disables the cursorline `line` option because of an upstream bug in Neovim core.
Related to https://github.com/neovim/neovim/issues/9800
**before**
**after**
=> fix: disable cursorline due to Neovim bug

lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/ui/colors.lua
- **add the forgotten colors**
- **get max numbers**
- **use the max value to determine width**
The telescope picker for `pr changes` was missing the colors and the width is now dynamic based on the results.
=> Add colors to `Octo pr changes` and improve width

lua/octo/reviews/file-panel.lua
Octo's panel sets the `'cursorline'` option, but it wouldn't show up if users had `'cursorlineopt'` globally configured to `"number"`, since the option `'number'` is disabled.
NONE
Added the new option for the panel
Should be straightforward, but if you wanna make sure, try setting  `'cursorlineopt'` globally to `"number"`
---
=> fix(panel): set cursorlineopt to line

README.md, lua/octo/ui/colors.lua, lua/octo/ui/writers.lua
I cannot find any info on `hl-NormalFront`. I assume it's a typo and should be `hl-NormalFloat`
NONE
=> fix: set valid highlight for OctoFilePanelFileName

lua/octo/pickers/snacks/provider.lua, lua/octo/reviews/init.lua, lua/octo/workflow_runs.lua
I noticed that a few `vim.fn.json_...` calls remain in the codebase while most of them already use the newer `vim.json` API. Not sure if something else needs to be done here.
NONE
=> refactor: switch remaining `vim.fn.json_...` calls to `vim.json`

lua/octo/ui/colors.lua
```lua
require "octo.ui.colors".octo_highlight_groups("Example text")
```
```
Group                          fg         bg         bold       italic     underline  Example
--------------------------------------------------------------------------------------------------
OctoBubbleDelimiterGrey        #2a354c    none       no         no         no         Example text
OctoFilePanelTitle             #58a6ff    none       yes        no         no         Example text
OctoFilePanelCounter           #6f42c1    none       yes        no         no         Example text
OctoViewer                     #000000    #58a6ff    no         no         no         Example text
OctoEditable                   none       #3c3836    no         no         no         Example text
OctoStrikethrough …
```
=> Add helper to display all hightlight groups

README.md, doc/octo.txt, lua/octo/commands.lua, lua/octo/gh/mutations.lua
This allows users to close a discussion with `:Octo discussion close`
- **add the required mutation**
- **add the command**
- **add the command to documentation**
- **add documentation for mark and unmark**
=> Add `:Octo discussion close` command

README.md, doc/octo.txt, lua/octo/commands.lua, lua/octo/gh/queries.lua, lua/octo/pickers/telescope/entry_maker.lua, lua/octo/pickers/telescope/provider.lua
This adds the `:Octo discussion search` command. It defaults to the current repo
`Octo search` can also be used to search discussions but `is:discussion` needs to be added to the search query.
For example, `Octo search is:discussion repo:pwntester/octo.nvim category:"Show and Tell"`
- **add discussion information to search**
- **implement for the telescope picker**
- **add the command**
- **add documentation for the command**
- **default to the current repo**
=> Add `:Octo discussion search` command

README.md, doc/octo.txt, lua/octo/commands.lua
Following https://github.com/pwntester/octo.nvim/pull/952, this allows the user to access the parent with the `Octo parent edit` command. 
Use <C-o> to go back to the previous buffer.
- **add `Octo parent edit` command**
- **add documentation for the command**
=> Add `Octo parent edit` command

lua/octo/completion/search.lua, lua/octo/gh/queries.lua
Upon searches with repo:, the user or organization can be searched with <Tab> until there is a "/". 
After, the repositories for that owner will be shown as completion
https://github.com/user-attachments/assets/8b57d805-bb0b-44d3-9a0c-15dece411a32
- **add repo, user, and organization information**
- **add logic for repo:**
=> Add user and repo completion with repo: argLead

lua/octo/completion/search.lua
Search queries without "repo:"  will use the default labels from GitHub
=> Use default labels for completions without repo

.github/ISSUE_TEMPLATE/bug_report.md, lua/octo/commands.lua, lua/octo/pickers/fzf-lua/pickers/gists.lua, lua/octo/pickers/fzf-lua/pickers/utils.lua, lua/octo/pickers/snacks/provider.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/utils.lua, lua/octo/workflow_runs.lua
Whole bunch of the same that is done with the `utils.copy_url` function
https://github.com/pwntester/octo.nvim/blob/064a71581dbd9b50b289cdb9910a4d124326164f/lua/octo/utils.lua?plain=1#L1798-L1802
- **add GitHub CLI version to bug template**
- **conslidate the copy_url**
=> consolidate copy url

lua/octo/pickers/fzf-lua/previewers.lua
The query was updated but not changed in `fzf` previewer. 
Can see this by running `:Octo repo list` with the fzf picker
Brought up here : https://github.com/pwntester/octo.nvim/discussions/939
=> Fix query used in fzf repo previewer

lua/octo/ui/writers.lua
Safely get the user for the commit header
Hi @nekowasabi, can you take a look at this a see if it fixes your issue
Some good searches to try out
`:Octo search is:pr involves:ghost`
`:Octo search is:pr author:ghost`
Closes #1012
=> Safely get the user for the commit header

README.md, lua/octo/config.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/workflow_runs.lua
Issue: #449
Added the following keybindings to **buffer** and **telescope**:  
- **`<C-o>`** → Rerun workflow  
- **`<C-f>`** → Rerun failed workflow  
- **`<C-x>`** → Cancel workflow
=> feat: `gh run rerun|cancel`

lua/octo/init.lua
Color configuration being done inside the `setup` function is causing the following issue, when performed alongside some color scheme configurations:
Fixes #1010 
Changed the `colors.setup` call from the setup call to autocmd.
Configure a color scheme and check if the error is present in the initialization.
=> Changes colors.setup call from setup() to update_layout_for_current_file

lua/octo/pickers/snacks/provider.lua
Implements a picker using the snacks provider for picking issue templates, which is used when creating issues.
NONE
Nothing special here.
Set `picker = "snacks"` and run `:Octo issue create`
No documentation changes needed.
=> feat: implement `issue_templates` picker for snacks provider

lua/octo/gh/queries.lua, lua/octo/pickers/snacks/provider.lua
This PR implements the search functionality for the snacks picker. 
Fixes #1046
I looked at previous implementations as well as the implementations for telescope and fzf-lua.
I also modified some of the queries to retrieve some information that was useful for displaying and checking the items in the search, but I'm not sure if you'd prefer some alternative?
Try setting `picker = "snacks"` and run
```
:Octo issue search
:Octo pr search
:Octo discussion search
:Octo search <query>
```
This PR does not yet implement `:Octo repo search`. I found that this was working for the telescope picker but that it wasn't listed anywhere. I tried to implement it but I couldn't wrap my head around how the snacks picker deals with this kind of live search. Maybe someone else can step in?
=> Provider snacks search

lua/octo/commands.lua, lua/octo/init.lua, lua/octo/ui/colors.lua
This PR removes the echoed highlight that occurs on some setups and improves colors setup performances
Fixes #1010
- replace `vim.cmd` calls by native `vim.api.nvim_set_hl()` calls as they are faster, and they avoid the string transformation for each highlight
- ensure that colors initialization is called once instead of each time a buffer or a command is executed (noticed with debug printing), and before `signs.setup()` which seemed to be triggering the `OctoEditable xxx cleared` because `colors.setup()` was redefining some already in use highlights
I currently use it (the echo `OctoEditable xxx cleared` was breaking with some plugins).
Also I was able to reproduce the issue 100% of times and with this PR I am not able anymore.
My reproducible setup was:
- just run nvim, the message was …
=> fix(colors): use lua api to set highlights and initialize colors once (fix #1010)

lua/octo/ui/colors.lua
This PR fixes the internal `get_fg()` helper from `colors` module.
The existing helper was not fetching the `fg` (`guifg` in highlight command) attribute but the `ctermfg` which is not compatible using `vim.api.nvim_get_hl()` (it's an integer that need to be passed as `ctermfg` parameter, not `fg`, but was silently working with the highlight command).
Also, `synIDattr()` + `nvim_get_hl_id_by_name()` was almost always returning a value, even if no hl_group was found.
Fixes #1056 
(I provided a fix to his config, bug it allowed me to spot this issues when no color scheme is loaded)
I used the dedicated `vim.api.nvim_get_hl()` API which doesn't silently fallback on `ctermfg`.
It results in the `get_fg()` returning the real `fg` for the given highlight and returning `nil` when there is no …
=> fix(colors): `get_fg()` was getting `fg` but `ctermfg`

README.md, lua/octo/config.lua, lua/octo/pickers/snacks/provider.lua, lua/tests/octo/config_spec.lua
- Added support for snacks-specific actions in the picker.
- Updated validation to include snacks configuration.
- Refactored existing actions to integrate with snacks.
- Improved tests to cover new snacks functionality.
Fixes #1059 
1.  **Configuration:** Modified `lua/octo/config.lua` to:                                                                        
*   Add `"snacks"` to the list of valid pickers.                                                                             
*   Define the new `OctoPickerConfigSnacks` and `OctoSnacksActionItem` types.                                                
*   Add the `picker_config.snacks` table with an `actions` sub-table (using an array-of-tables structure for actions) to the default configuration. …
=> feat(snacks): enhance picker configuration and actions

lua/octo/pickers/snacks/provider.lua
The current issue lists looks like this for the snacks picker:
There biggest issue here is that the highlight disappears across the issue title. This PR also changes the format to be in line with what the search function currently uses, which use a different highlight group for the issue id.
NONE
=> feat(snacks): improve format for issue list

README.md, lua/octo/config.lua, lua/octo/pickers/telescope/provider.lua
These changes add a new binding `<localleader>nd` inside of the notification picker which marks a notification as done. 
It's needed because this action clears the notification from the GitHub UI, the current binding for reading a notification leaves the notification in the UI, even though it removes the notification from octo. 
Fixes #1064 
I created that issue since the CONTRIBUTING.md file mentioned that each PR should be linked to an issue. Let me know if that was not the intention. 
I've added a new function which sends a delete request on the picked notification, rather than a PATCH request marking it as read. From the [GitHub API docs](https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#mark-a-thread-as-done) this is how you mark a notification as complete. …
=> feat: add command for marking notification as done

README.md
The README mapping was different than the actual mapping in the configuration. This makes them match.
=> Make notification mapping match the config

lua/octo/constants.lua
adjust the user pattern to also find users from enterprise organizations in github 
Fixes #1070
added `_` to pattern so users from enterprise organization can be queried via gh cli
move to a mention of user from enterprice org in an issue or similar, hover should appear with the short info of the user
=> Adjust user pattern to also find users from enterprise orgs

lua/octo/model/octo-buffer.lua, lua/octo/model/pull-request.lua, lua/octo/reviews/file-entry.lua, lua/octo/reviews/thread-panel.lua
There were various different issues when you tried to use the `:Octo review commit` command. These bugs are listed as follows:
1. When you ran the `:Octo review commit` command, and then picked a specific commit, it would be stuck on processing / loading the diffed files but it would never work.
2. Even after fixing 1, when you posted a review commit comment on a certain line, the comment would show up on a different line in the actual GitHub PR.
3. Even after fixing 1 & 2, the comment that you actually posted for a commit would end up leaking through the different diffed files' buffers and even if it showed up on the correct line in the GitHub PR, the thread (and the Octo thread preview hint in the diffed buffers) would show up on the wrong line.
This PR fixes all that.
Fixes #1061
Fixes …
=> Fix broken `:Octo review commit` command workflow

lua/octo/ui/colors.lua
This PR prevent HL groups from being overwritten if they already exists (aka. provided by a theme or the user)
It fixes this case: https://github.com/pwntester/octo.nvim/issues/1010#issuecomment-2878240118
By checking the hl groups existence before setting them (it was already done for linked hl groups)
Themes with Octo integration should have all treir highlight groups.
=> fix(colors): don't overwrite highlight groups if they exists

README.md, lua/octo/config.lua, lua/octo/pickers/telescope/provider.lua
Adds the unsubscribe keymap, which unsubscribes the user from further notifications, marks the notifications as read and removes the notification from the picker list.
=> feat(notifications): add unsubscribe keymap

lua/octo/gh/init.lua
Use environment variable `DBUS_SESSION_BUS_ADDRESS`  to access token in keyring otherwise every `gh` will fail in Octo.
Fixes: #1066 
Inject environment variable `DBUS_SESSION_BUS_ADDRESS` when running `gh`  commands
See #1066 for details
=> fix(env): add DBUS env var to enable accessing token in keyring

README.md, lua/octo/commands.lua, lua/octo/config.lua
It's intended to make easy to create prs with the title equal to the local branch name.
I created the var to the config, and into the save_pr command, i used it to check if it's true, in case of been, i replaced the title variable with the remote_branch var, that cames from the create_pr call.
Set the var to be true on the config, and then run the `:Octo pr create`, one should see the title as the current branch name.
=> Adds a branch name as title for PR config

lua/octo/constants.lua, lua/octo/gh/fragments.lua, lua/octo/gh/queries.lua, lua/octo/init.lua, lua/octo/model/octo-buffer.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
Renders releases with the format `octo://<owner>/<repo>/release/<tag>`. This will be used for notifications to have something to preview and look at.
There is decent room for improvement here, but wanted to get a start here an incrementally improve it.
NONE
Writing to the buffer was fairly standard, though writing the `Pre-release` and `Latest` title virtual text is not using the `write_status` util, but rather more one-off.
Some slight changes to how we parse the `octo://` uri so that releases can be re-used here. In that previously only numbers we allowed for that last part of the uri, but now it's alphanumeric + numbers. This might not be comprehensive, but it was enough for my uses.
`:e octo://neovim/neovim/release/nightly`
- Need to add more features here before adding to …
=> feat: render release

lua/octo/ui/writers.lua
Adding a file comment still shows the thread snippet because the diffHunk ends up being an empty string. We don't handle this case since we end up showing an empty box with a bunch of new lines.
Add a file comment to a PR and view it in octo.
=> fix(pull request): do not show comment code block when empty

lua/octo/ui/bubbles.lua
Adds in the missing colors in the type enum
CC: @PeterCardenas 
Closes #1100
Add all of the colors here: 
https://docs.github.com/en/graphql/reference/enums#issuetypecolor
octo://ghostty-org/ghostty/issue/7557
octo://ghostty-org/ghostty/issue/7591
=> add missing colors in the enum

lua/octo/ui/writers.lua
Some files do not have treesitter parsers, or the user just might not have them installed. So we check against it before trying to parse and highlight.
=> fix: do not error when code block has no parser

lua/octo/model/octo-buffer.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
Review decisions don't get written to the timeline if they don't have a comment/body. This is mostly fine, but I would still like to see if someone stamped my PR, which this allows for.
closes #1018
I copied over some of the logic from `writers.write_comment`, leaving out the readonly marker since there's no comment to write.
Try making a review decision on this PR without a comment and with a comment.
=> fix: write review decision when empty

lua/octo/commands.lua, lua/octo/gh/init.lua, lua/octo/gh/mutations.lua, lua/octo/utils.lua
Allows for adding multiple reviewers/assignees at once. Implementation is a bit hacky in that there is a request for the user id for each user, when it probably could be done in a single request. Though, I don't usually think there's so many reviewers that it matters.
`Octo reviewer add user1 user2`
`Octo assignee add user1 user2`
=> feat: add multiple reviewers/assignees at once

lua/octo/completion/init.lua
The last argument of user commands gets duplicated. For example if you type `Oct notifications list `, I get `list` as a completion item. This PR fixes that and also handles the case where there's multiple spaces between arguments.
doesn't really address it, but we can probably close #347
`Octo notifications list ` completes nothing
`Octo  notifications ` completes `list`
=> fix: properly handle white space user cmd completion

lua/octo/ui/window.lua
The content of the floating window was positioned at the same y offset as the header. This was because the `header` field was not being passed. Made the types prevent this by making it `boolean` instead of `string?`
`:Octo pr checks` on this PR
=> fix: floating window content offset

.pre-commit-config.yaml, .stylua.toml
This fixes the precommit hook for stylua.
the goto syntax is a syntax in lua5.2, and its syntax conflicts with luau. thus we must specify the syntax for stylua. additionally we should install stylua from github releases because installing with cargo only embeds the lua5.1 syntax, while the github release has all syntaxes, but requires disambiguation
=> chore: fix stylua precommit step

lua/octo/utils.lua
Seems we used to have a red `D` in the file panel, maybe the api changed or something since then tho. Adds it back while probably keeping backwards compatibility.
=> fix: add red D for removed files in review file panel

lua/octo/commands.lua, lua/octo/config.lua, lua/octo/gh/queries.lua, lua/octo/init.lua, lua/octo/model/octo-buffer.lua, lua/octo/navigation.lua, lua/octo/pickers/fzf-lua/pickers/project_cards.lua, lua/octo/pickers/fzf-lua/pickers/project_cards_v2.lua, lua/octo/pickers/telescope/provider.lua, lua/octo/ui/writers.lua, lua/octo/utils.lua
Discourage use of `OctoBuffer.node` in favor of `OctoBuffer:issue()`, `OctoBuffer:pull_request()`, `OctoBuffer:repository()`, `OctoBuffer:release()`, and `OctoBuffer:discussion()`.
This removes the need for casting on the `node` property since it is abstracted in a safe manner.
=> chore: improve typing of OctoBuffer.node

lua/octo/commands.lua
Fixes an error in a `copy_sha` method, where we're not executing the `:pull_request` method properly. thought this would incur a type error 🤔
=> fix: copy_sha error

lua/octo/config.lua, lua/octo/pickers/snacks/provider.lua
- Adds `commits` picker for snacks
- Adds `review_commits` picker for snacks
- Fixes #1032.
- Fixes #1045.
Saw how they are implemented in other pickers and done the same for snacks.
I've tested this extensively in repos that have PRs and it works.
You can test this using snacks to review this PR since it has 2 commits 😄.
I'm not familiar with testing and listing in Lua, I mainly use Lua for my own stuff like NeoVim configs.
- [] Documentation updates in README.md and doc/octo.txt
=> feat(snacks): `commits` and `review_commits` picker

lua/octo/utils.lua
Fixes a bug where PR review comments on visual selections fail when selecting text from bottom to top. 
When selecting code from bottom to top (e.g., starting at line 10 and selecting up to line 8), the comment creation would:
- Show an empty snippet in the comment buffer
- Display reversed line numbers (10:8 instead of 8:10)  
- Fail with an error when attempting to save: `attempt to index field 'thread' (a userdata value)`
Fixes https://github.com/pwntester/octo.nvim/issues/476.
The issue was that `utils.get_lines_from_context()` returned line numbers in the order they were selected, not normalized. When selecting bottom-to-top, this resulted in `line_start > line_end`, breaking downstream code that expects normalized ranges.
Added a simple swap in `lua/octo/utils.lua` to ensure …
=> fix(comment): normalize lines on reversed visual selection

README.md
This PR adds a note to the README concerning possibly running into authentication errors that I experienced not fully understanding the need to add ssh aliases to the setup config.
I didn't create an issue 🤷‍♂️. It felt easier just to update the README since I wasn't making any code changes. If you need me to, just let me know.
"NONE"
I forked the repo, cloned locally, checked out my branch, and typed in the addition.
The creator should verify whether this is correct.
Thanks for creating this project. Haven't gotten to fully use it yet, but it looks awesome.
Didn't change any code so I did not run any tests or linters.
=> docs: add aside concerning ssh aliases when getting unauthenticated errors

lua/octo/mappings.lua
A small issue was missed in https://github.com/pwntester/octo.nvim/pull/1122 where the new `<localleader>C` mapping to invoke the `review_commits` command doesn't pass in the appropriate `callback` function needed to display the selected commit from the picker. 
The existing `Octo review commit` command already handles this correctly, so I just copied over the same code to the `review_commits` mapping.
Fixes #1169
Just looked at the traceback in #1169 and figured out that the `callback` argument wasn't getting provided.
Open up a review at execute the `<localleader>C` mapping to verify it works now.
=> fix: review commits mapping not providing callback

lua/octo/ui/writers.lua
When a PR is in draft but not closed, it's pretty confusing that we show "OPEN" and the "DRAFT" state. GitHub only shows the draft badge, so I updated it to only show the draft badge here as well. Also cleaned up the rendering logic so that we don't add the background highlight on whitespace between the badges.
=> fix(pr): do not show OPEN status when in DRAFT state

lua/octo/gh/mutations.lua
the fragment concatenations for pull requests are missing both `fragments.convert_to_draft_event` and `fragments.ready_for_review_event`.
- fixes https://github.com/pwntester/octo.nvim/issues/1172
add missing fragments to create PR and update PR state.
create PR using Octo.nvim
=> fix: add missing fragments
